In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import pytz
import yfinance as yf
import pyodbc
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import time
import logging
import pandas as pd
from truedata import TD_hist
import requests

In [2]:
def fetch_truedata_history(
    ticker_list: list,
    duration: str = '1 Y',
    bar_size: str = 'EOD',
    sleep_time: float = 0.1
) -> tuple[pd.DataFrame, list]:
    """
    Fetches historical data from TrueData for a list of tickers.

    Parameters
    ----------
    username : str
        TrueData username.
    password : str
        TrueData password.
    ticker_list : list
        List of ticker symbols to fetch data for.
    duration : str, optional
        Duration of data (e.g., '1 Y', '25 Y', etc.). Default is '1 Y'.
    bar_size : str, optional
        Bar size for data ('EOD', 'WEEK', etc.). Default is 'EOD'.
    sleep_time : float, optional
        Delay between API calls to avoid throttling. Default is 0.2 seconds.

    Returns
    -------
    final_df : pd.DataFrame
        Combined DataFrame of all tickers' historical data.
    error_list : list
        List of tickers that failed to fetch.
    """
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    username = 'tdwsf695'
    password = 'ocean@695'
    # Initialize connection
    td_hist = TD_hist(username, password)
    df_list = []
    error_list = []
    for ticker in ticker_list:
        try:
            df = td_hist.get_historic_data([ticker], duration=duration, bar_size=bar_size)

            df['Ticker'] = ticker
            # Check column names and rename accordingly
            rename_dict = {}
            if 'timestamp' in df.columns:
                rename_dict['timestamp'] = 'Date'
            elif 'datetime' in df.columns:
                rename_dict['datetime'] = 'Date'
            elif 'date' in df.columns:
                rename_dict['date'] = 'Date'
            rename_dict.update({
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'open': 'Open'
            })
            df = df.rename(columns=rename_dict)

            df_list.append(df)
            logging.info(f"Fetched data for {ticker} ({len(df)} rows).")
            time.sleep(sleep_time)

        except Exception as e:
            logging.error(f"Failed to fetch data for {ticker}: {e}")
            error_list.append(ticker)

    final_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
    return final_df, error_list

In [3]:
import numpy as np
import pandas as pd
from dateutil.relativedelta import relativedelta

def process_portfolio(nav_df, ticker_data, initial_value=75, output_file=None):
    """
    Process portfolio allocation and returns final dataframe with portfolio performance.

    Parameters
    ----------
    nav_df : pd.DataFrame
        Dataframe with at least ['Year-Month', 'Ticker'] columns.
    get_individual_stock_data : function
        Function to fetch OHLC data. Must accept (tickers, start_date, end_date) and return DataFrame with ['Date','Ticker','Close'].
    initial_value : float
        Initial portfolio allocation value (default=75).
    debt_ticker : str
        Ticker used as debt/alternative asset (default 'MOGSEC.NS').
    output_file : str or None
        If provided, saves the final dataframe to Excel.

    Returns
    -------
    pd.DataFrame
        Final dataframe with portfolio values.
    """
    df_lis = []
    last_month_value = {}
    year_months = nav_df['Year-Month'].unique()
    for i, year_month in enumerate(year_months):
        print(f"\nProcessing: {year_month}")
        print("Last Month Value:", last_month_value)

        tickers = nav_df[nav_df['Year-Month'] == year_month]['Ticker'].unique()
        year_month_date = pd.to_datetime(f"{year_month}-01")


        prev_month_start = (year_month_date - relativedelta(months=2)).strftime('%Y-%m-%d')
        curr_month_start = year_month_date.strftime('%Y-%m-%d')
        curr_month_end = (year_month_date + pd.offsets.MonthEnd(0)).strftime('%Y-%m-%d')

        # --- Fetch stock data ---
        # stock_data = get_individual_stock_data(tickers, prev_month_start, curr_month_end)
        stock_data = (
            ticker_data[(ticker_data['Date'] >= prev_month_start)
            & (ticker_data['Date'] <= curr_month_end) 
            & (ticker_data['Ticker'].isin(tickers))])
        
        # % change
        stock_data['%change'] = stock_data.groupby('Ticker')['Close'].pct_change()
        # Filter current month
        stock_data_flt = stock_data[
            (stock_data['Date'] >= curr_month_start) & (stock_data['Date'] <= curr_month_end)
        ].copy()

        print(stock_data_flt)

        # --- Portfolio allocation logic ---
        if len(last_month_value) == 0:
            # First month → allocate initial portfolio equally
            allocation_per_stock = initial_value / len(tickers)
            stock_allocations = {t: allocation_per_stock for t in tickers}
        else:
            # Continue portfolio
            stock_allocations = {t: last_month_value[t] for t in tickers if t in last_month_value}

            # Pool value of dropped stocks
            dropped_stocks = [t for t in last_month_value if t not in tickers]
            dropped_value = sum(last_month_value[t] for t in dropped_stocks)

            # New stocks → share the dropped value equally
            new_stocks = [t for t in tickers if t not in last_month_value]
            if new_stocks:
                allocation_per_stock = dropped_value / len(new_stocks)
                for t in new_stocks:
                    stock_allocations[t] = allocation_per_stock

        # Apply allocations into dataframe
        for tkr, init_value in stock_allocations.items():
            tkr_idx = stock_data_flt[stock_data_flt['Ticker'] == tkr].index
            stock_data_flt.loc[tkr_idx, 'Buy_Hold_Value'] = init_value * (
                (1 + stock_data_flt.loc[tkr_idx, '%change'].fillna(0)).cumprod()
            )

        # --- Update last month values ---
        last_month_value = (
            stock_data_flt.groupby('Ticker')['Buy_Hold_Value'].last().to_dict()
        )

        # --- Track total portfolio value ---
        stock_data_flt['Total_Portfolio_Value'] = (
            stock_data_flt.groupby('Date')['Buy_Hold_Value'].transform('sum')
        )

        df_lis.append(stock_data_flt)

    
    final_df = pd.concat(df_lis).reset_index(drop=True)

    if output_file:
        final_df.to_excel(output_file, index=False)

    return final_df

In [4]:
import os
import pandas as pd

def prepare_and_process_portfolio(input_file, start_date, end_date, output_folder,
                                  process_portfolio,
                                  equity_allocation=75, gold_allocation=25):
    """
    Prepare portfolio dataframe with momentum stocks + GOLDBEES and process performance.

    Parameters
    ----------
    input_file : str
        Path to momentum Excel file (with End_Date, Ticker columns).
    start_date : str (YYYY-MM-DD)
        Start date for filtering.
    end_date : str (YYYY-MM-DD)
        End date for filtering.
    output_folder : str
        Folder to save output file.
    get_individual_stock_data : function
        Function to fetch stock NAV/price data.
    process_pocrtfolio : function
        Function to process equity portion of portfolio.
    process_gold : function
        Function to process gold portion of portfolio.
    equity_allocation : int, optional
        Initial allocation to equities (default=75000).
    gold_allocation : int, optional
        Initial allocation to gold (default=25000).

    Returns
    -------
    final_df : pd.DataFrame
        Combined portfolio dataframe.
    """

    # Load and clean
    nav_df = pd.read_excel(input_file).rename(columns={'End_Date': 'Date'})
    nav_df['Date'] = pd.to_datetime(nav_df['Date'])
    nav_df = (
        nav_df[(nav_df['Date'] >= start_date) & (nav_df['Date'] <= end_date)]
        .reset_index(drop=True)[['Date', 'Ticker']]
    )
    nav_df['Year-Month'] = nav_df['Date'].dt.to_period('M').astype(str)
    stocks = pd.read_excel(input_file)

    # Add GOLDBEES for each unique date
    goldbees_df = pd.DataFrame({
        'Date': nav_df['Date'].unique(),
        'Ticker': 'GOLDBEES'
    })
    goldbees_df['Year-Month'] = pd.to_datetime(goldbees_df['Date']).dt.to_period('M').astype(str)
    # print(goldbees_df)

    # Combine
    concat_df = (
        pd.concat([nav_df, goldbees_df], ignore_index=True)
          .sort_values(['Date', 'Ticker'])
          .reset_index(drop=True)
    )

    # symbol_list = stocks['Ticker'].unique()
    # ticker_data = fetch_truedata_history(
    #     ticker_list = symbol_list,
    #     duration = '5 Y',
    #     bar_size = 'EOD',
    #     sleep_time= 0.1
    # )[0]
    # final_df = process_portfolio(concat_df, ticker_data, equity_allocation)

    
    # Split
    ticker_df = concat_df.query("Ticker != 'GOLDBEES'")
    symbol_list = ticker_df['Ticker'].unique()
    ticker_data_other_stocks = fetch_truedata_history(
        ticker_list = symbol_list,
        duration = '10 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0]

    
    gold_df = concat_df.query("Ticker == 'GOLDBEES'")
    symbol_list = gold_df['Ticker'].unique()
    ticker_data_gold = fetch_truedata_history(
        ticker_list = symbol_list,
        duration = '10 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0]
    # print(gold_df)

    # Process
    final_df_other_stocks = process_portfolio(ticker_df, ticker_data_other_stocks, equity_allocation)
    # final_df_gold = process_gold(gold_df, get_individual_stock_data, gold_allocation)
    final_df_gold = process_portfolio(gold_df, ticker_data_gold, gold_allocation)


    # Merge results
    final_df = (
        pd.concat([final_df_other_stocks, final_df_gold], ignore_index=True)
          .sort_values(['Date', 'Ticker'])
          .reset_index(drop=True)
    )


    # --- ensure output folder exists ---
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # --- extract middle folder name from input path ---
    middle_folder = os.path.basename(os.path.dirname(input_file))
    # e.g. for path ".../nifty500_21April2025_results/master_momentum_summary.xlsx"
    # middle_folder = "nifty500_21April2025_results"

    # --- create output filename using middle folder ---
    output_file = os.path.join(output_folder, f"{middle_folder}_gold_buy&hold_returns.xlsx")

    # --- save output ---
    # final_df.to_excel(output_file, index=False)
    print(f"✅ Final output saved to: {output_file}")

    return final_df

In [5]:
#NSE500

In [6]:
final_df = prepare_and_process_portfolio(
    input_file="Stocks/Nifty_500_2025_Apr_20_stocks_results/master_momentum_summary.xlsx",
    start_date="2023-04-01",
    end_date=date.today().strftime('%Y-%m-%d'),
    output_folder="Trials",
    process_portfolio=process_portfolio
)

import plotly.express as px

# ✅ Group by Date and calculate total portfolio value
portfolio_summary = (
    final_df.groupby("Date", as_index=False)["Buy_Hold_Value"].sum()
)

# ✅ Plot with Plotly
fig = px.line(
    portfolio_summary,
    x="Date",
    y="Buy_Hold_Value",
    title="Buy_Hold_Value Over Time",
    labels={"Date": "Date", "Buy_Hold_Value": "Buy_Hold_Value"},
    markers=True
)

fig.update_traces(line=dict(width=2))
fig.update_layout(width=1000,   # 🔑 width
                  height=500)    # 🔑 height

fig.show()

(2026-01-22 09:47:37,269) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
2026-01-22 09:47:37,269 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-22 09:47:37,620 - INFO - Fetched data for ABCAPITAL (2081 rows).
2026-01-22 09:47:38,001 - INFO - Fetched data for ANANDRATHI (1021 rows).
2026-01-22 09:47:38,431 - INFO - Fetched data for BANKBARODA (2477 rows).
2026-01-22 09:47:38,855 - INFO - Fetched data for BANKINDIA (2477 rows).
2026-01-22 09:47:39,288 - INFO - Fetched data for BOSCHLTD (2477 rows).
2026-01-22 09:47:39,720 - INFO - Fetched data for CANBK (2477 rows).
2026-01-22 09:47:40,167 - INFO - Fetched data for CUMMINSIND (2477 rows).
2026-01-22 09:47:40,640 - INFO - Fetched data for FINCABLES (2477 rows).
2026-01-22 09:47:41,095 - INFO - Fetched data for GODFRYPHLP (2477 rows).
2026-01-22 09:47:41,535 - INFO - Fetched data for J&KBANK (2477 rows).
2026-01-22 09:47:42,025 - INFO - Fetched data for JINDALSAW (2477 rows).
2026-01-22 09:47:42,478 - INFO - Fetched data for JSL (2477 rows).
2026-01-22 09:47:42,907 - INFO - Fetched data for KAYNES (788 rows).
2026-01-22 09:47:43,352 - INFO - Fetched data for KIRLOSENG (2477 rows).
2026-01-22 09:47:43,829 - INFO - Fetched data for NCC (2477 rows).
2026-01-22 09:47:44,277 - INFO - Fetched data for PFC (2477 rows).
2026-01-22 09:47:44,732 - INFO - Fetched data for PNB (2477 rows).
2026-01-22 09:47:45,223 - INFO - Fetched data for RKFORGE (2477 rows).
2026-01-22 09:47:45,671 - INFO - Fetched data for SHREECEM (2477 rows).
2026-01-22 09:47:46,101 - INFO - Fetched data for TITAGARH (2477 rows).
2026-01-22 09:47:46,538 - INFO - Fetched data for ANANTRAJ (2477 rows).
2026-01-22 09:47:46,980 - INFO - Fetched data for CYIENT (2477 rows).
2026-01-22 09:47:47,454 - INFO - Fetched data for GLENMARK (2477 rows).
2026-01-22 09:47:47,906 - INFO - Fetched data for HINDPETRO (2477 rows).
2026-01-22 09:47:48,333 - INFO - Fetched data for IRCON (1814 rows).
2026-01-22 09:47:48,780 - INFO - Fetched data for JBMA (2477 rows).
2026-01-22 09:47:49,253 - INFO - Fetched data for JWL (2477 rows).
2026-01-22 09:47:49,687 - INFO - Fetched data for KPITTECH (1677 rows).
2026-01-22 09:47:50,167 - INFO - Fetched data for LINDEINDIA (2477 rows).
2026-01-22 09:47:50,626 - INFO - Fetched data for ABB (2477 rows).
2026-01-22 09:47:51,066 - INFO - Fetched data for APARINDS (2477 rows).
2026-01-22 09:47:51,527 - INFO - Fetched data for CHENNPETRO (2477 rows).
2026-01-22 09:47:51,979 - INFO - Fetched data for CHOLAFIN (2477 rows).
2026-01-22 09:47:52,431 - INFO - Fetched data for GRAVITA (2477 rows).
2026-01-22 09:47:52,875 - INFO - Fetched data for ITC (2477 rows).
2026-01-22 09:47:53,299 - INFO - Fetched data for POLYCAB (1679 rows).
2026-01-22 09:47:53,697 - INFO - Fetched data for POWERINDIA (1445 rows).
2026-01-22 09:47:54,151 - INFO - Fetched data for RAMCOCEM (2477 rows).
2026-01-22 09:47:54,588 - INFO - Fetched data for VBL (2284 rows).
2026-01-22 09:47:55,021 - INFO - Fetched data for AUROPHARMA (2477 rows).
2026-01-22 09:47:55,445 - INFO - Fetched data for ELECON (2477 rows).
2026-01-22 09:47:55,875 - INFO - Fetched data for EXIDEIND (2477 rows).
2026-01-22 09:47:56,326 - INFO - Fetched data for LTF (2477 rows).
2026-01-22 09:47:56,753 - INFO - Fetched data for MAHSEAMLES (2477 rows).
2026-01-22 09:47:57,177 - INFO - Fetched data for RECLTD (2477 rows).
2026-01-22 09:47:57,630 - INFO - Fetched data for SIEMENS (2477 rows).
2026-01-22 09:47:58,051 - INFO - Fetched data for ZENSARTECH (2477 rows).
2026-01-22 09:47:58,439 - INFO - Fetched data for ZFCVINDIA (946 rows).
2026-01-22 09:47:58,873 - INFO - Fetched data for ADANIPORTS (2477 rows).
2026-01-22 09:47:59,299 - INFO - Fetched data for NEULANDLAB (2477 rows).
2026-01-22 09:47:59,728 - INFO - Fetched data for SARDAEN (2477 rows).
2026-01-22 09:48:00,158 - INFO - Fetched data for USHAMART (2477 rows).
2026-01-22 09:48:00,554 - INFO - Fetched data for ANGELONE (1316 rows).
2026-01-22 09:48:00,988 - INFO - Fetched data for BSE (2223 rows).
2026-01-22 09:48:01,441 - INFO - Fetched data for HBLENGINE (2477 rows).
2026-01-22 09:48:01,831 - INFO - Fetched data for KALYANKJIL (1196 rows).
2026-01-22 09:48:02,263 - INFO - Fetched data for LUPIN (2477 rows).
2026-01-22 09:48:02,709 - INFO - Fetched data for NATCOPHARM (2477 rows).
2026-01-22 09:48:01,366 - INFO - Fetched data for CHOLAHLDNG (2065 rows).
2026-01-22 09:48:01,752 - INFO - Fetched data for ETERNAL (1117 rows).
2026-01-22 09:48:02,181 - INFO - Fetched data for HUDCO (2153 rows).
2026-01-22 09:48:02,604 - INFO - Fetched data for RBLBANK (2329 rows).
2026-01-22 09:48:03,028 - INFO - Fetched data for SUZLON (2477 rows).
2026-01-22 09:48:03,450 - INFO - Fetched data for TARIL (2477 rows).
2026-01-22 09:48:03,873 - INFO - Fetched data for TATAINVEST (2477 rows).
2026-01-22 09:48:04,329 - INFO - Fetched data for BSOFT (2477 rows).
2026-01-22 09:48:04,748 - INFO - Fetched data for DIXON (2070 rows).
2026-01-22 09:48:05,178 - INFO - Fetched data for KIRLOSBROS (2477 rows).
2026-01-22 09:48:05,607 - INFO - Fetched data for MRPL (2477 rows).
2026-01-22 09:48:06,032 - INFO - Fetched data for SUPREMEIND (2477 rows).
2026-01-22 09:48:06,468 - INFO - Fetched data for BHEL (2477 rows).
2026-01-22 09:48:06,892 - INFO - Fetched data for GPIL (2477 rows).
2026-01-22 09:48:07,322 - INFO - Fetched data for MCX (2477 rows).
2026-01-22 09:48:07,750 - INFO - Fetched data for NLCINDIA (2477 rows).
2026-01-22 09:48:08,186 - INFO - Fetched data for PRESTIGE (2477 rows).
2026-01-22 09:48:08,557 - INFO - Fetched data for SIGNATURE (576 rows).
2026-01-22 09:48:08,996 - INFO - Fetched data for SJVN (2477 rows).
2026-01-22 09:48:09,437 - INFO - Fetched data for DBREALTY (2477 rows).
2026-01-22 09:48:09,895 - INFO - Fetched data for GVT&D (2477 rows).
2026-01-22 09:48:10,284 - INFO - Fetched data for IREDA (535 rows).
2026-01-22 09:48:10,727 - INFO - Fetched data for NBCC (2477 rows).
2026-01-22 09:48:11,128 - INFO - Fetched data for RAILTEL (1215 rows).
2026-01-22 09:48:11,578 - INFO - Fetched data for TRENT (2477 rows).
2026-01-22 09:48:12,020 - INFO - Fetched data for GMDCLTD (2477 rows).
2026-01-22 09:48:12,475 - INFO - Fetched data for BAJAJ-AUTO (2477 rows).
2026-01-22 09:48:12,919 - INFO - Fetched data for BPCL (2477 rows).
2026-01-22 09:48:13,378 - INFO - Fetched data for DLF (2477 rows).
2026-01-22 09:48:13,824 - INFO - Fetched data for INOXWIND (2477 rows).
2026-01-22 09:48:14,270 - INFO - Fetched data for IOC (2477 rows).
2026-01-22 09:48:14,715 - INFO - Fetched data for NIACL (2032 rows).
2026-01-22 09:48:15,175 - INFO - Fetched data for OIL (2477 rows).
2026-01-22 09:48:15,625 - INFO - Fetched data for BDL (1942 rows).
2026-01-22 09:48:16,068 - INFO - Fetched data for EIHOTEL (2477 rows).
2026-01-22 09:48:16,515 - INFO - Fetched data for ZYDUSLIFE (2477 rows).
2026-01-22 09:48:17,003 - INFO - Fetched data for BEL (2477 rows).
2026-01-22 09:48:17,450 - INFO - Fetched data for COCHINSHIP (2094 rows).
2026-01-22 09:48:17,894 - INFO - Fetched data for HAL (1939 rows).
2026-01-22 09:48:18,349 - INFO - Fetched data for MOTILALOFS (2477 rows).
2026-01-22 09:48:18,800 - INFO - Fetched data for NHPC (2477 rows).
2026-01-22 09:48:19,273 - INFO - Fetched data for SAIL (2477 rows).
2026-01-22 09:48:19,722 - INFO - Fetched data for VOLTAS (2477 rows).
2026-01-22 09:48:20,169 - INFO - Fetched data for NATIONALUM (2477 rows).
2026-01-22 09:48:20,599 - INFO - Fetched data for RVNL (1682 rows).
2026-01-22 09:48:21,044 - INFO - Fetched data for TECHNOE (1771 rows).
2026-01-22 09:48:21,489 - INFO - Fetched data for THERMAX (2477 rows).
2026-01-22 09:48:21,970 - INFO - Fetched data for VEDL (2477 rows).
2026-01-22 09:48:22,759 - INFO - Fetched data for BLUESTARCO (2477 rows).
2026-01-22 09:48:23,642 - INFO - Fetched data for GODREJPROP (2477 rows).
2026-01-22 09:48:24,496 - INFO - Fetched data for INDUSTOWER (2477 rows).
2026-01-22 09:48:25,282 - INFO - Fetched data for JSWENERGY (2477 rows).
2026-01-22 09:48:26,117 - INFO - Fetched data for MOTHERSON (2477 rows).
2026-01-22 09:48:26,979 - INFO - Fetched data for SCHNEIDER (2477 rows).
2026-01-22 09:48:27,810 - INFO - Fetched data for BASF (2477 rows).
2026-01-22 09:48:28,754 - INFO - Fetched data for DOMS (520 rows).
2026-01-22 09:48:29,663 - INFO - Fetched data for M&M (2477 rows).
2026-01-22 09:48:30,531 - INFO - Fetched data for AJANTPHARM (2477 rows).
2026-01-22 09:48:31,353 - INFO - Fetched data for COLPAL (2477 rows).
2026-01-22 09:48:32,109 - INFO - Fetched data for COROMANDEL (2477 rows).
2026-01-22 09:48:32,920 - INFO - Fetched data for DEEPAKFERT (2477 rows).
2026-01-22 09:48:33,778 - INFO - Fetched data for EMAMILTD (2477 rows).
2026-01-22 09:48:34,569 - INFO - Fetched data for ERIS (2125 rows).
2026-01-22 09:48:35,343 - INFO - Fetched data for LTFOODS (551 rows).
2026-01-22 09:48:36,155 - INFO - Fetched data for NAVA (2477 rows).
2026-01-22 09:48:36,968 - INFO - Fetched data for DIVISLAB (2477 rows).
2026-01-22 09:48:37,751 - INFO - Fetched data for HSCL (2477 rows).
2026-01-22 09:48:38,468 - INFO - Fetched data for PCBL (999 rows).
2026-01-22 09:48:39,431 - INFO - Fetched data for PGEL (2477 rows).
2026-01-22 09:48:40,196 - INFO - Fetched data for PPLPHARMA (809 rows).
2026-01-22 09:48:41,039 - INFO - Fetched data for COFORGE (2477 rows).
2026-01-22 09:48:41,811 - INFO - Fetched data for COHANCE (1459 rows).
2026-01-22 09:48:42,655 - INFO - Fetched data for JMFINANCIL (2477 rows).
2026-01-22 09:48:43,453 - INFO - Fetched data for PERSISTENT (2477 rows).
2026-01-22 09:48:44,304 - INFO - Fetched data for WOCKPHARMA (2477 rows).
2026-01-22 09:48:45,066 - INFO - Fetched data for KIMS (1135 rows).
2026-01-22 09:48:45,878 - INFO - Fetched data for OFSS (2477 rows).
2026-01-22 09:48:46,706 - INFO - Fetched data for PEL (2394 rows).
2026-01-22 09:48:47,537 - INFO - Fetched data for FORTIS (2477 rows).
2026-01-22 09:48:48,364 - INFO - Fetched data for IPCALAB (2477 rows).
2026-01-22 09:48:49,179 - INFO - Fetched data for KFINTECH (761 rows).
2026-01-22 09:48:49,990 - INFO - Fetched data for LAURUSLABS (2256 rows).
2026-01-22 09:48:50,826 - INFO - Fetched data for PAYTM (1038 rows).
2026-01-22 09:48:51,678 - INFO - Fetched data for SAGILITY (297 rows).
2026-01-22 09:48:52,147 - INFO - Fetched data for WELCORP (2477 rows).
2026-01-22 09:48:52,681 - INFO - Fetched data for ZENTEC (2477 rows).
2026-01-22 09:48:53,103 - INFO - Fetched data for AIIL (437 rows).
2026-01-22 09:48:53,553 - INFO - Fetched data for ASTERDM (1960 rows).
2026-01-22 09:48:54,016 - INFO - Fetched data for CONCORDBIO (604 rows).
2026-01-22 09:48:54,528 - INFO - Fetched data for ECLERX (2477 rows).
2026-01-22 09:48:55,024 - INFO - Fetched data for INDHOTEL (2477 rows).
2026-01-22 09:48:55,518 - INFO - Fetched data for JSWHL (2477 rows).
2026-01-22 09:48:55,897 - INFO - Fetched data for LLOYDSME (627 rows).
2026-01-22 09:48:56,355 - INFO - Fetched data for MUTHOOTFIN (2477 rows).
2026-01-22 09:48:56,812 - INFO - Fetched data for BAJFINANCE (2477 rows).
2026-01-22 09:48:57,226 - INFO - Fetched data for FLUOROCHEM (1559 rows).
2026-01-22 09:48:57,674 - INFO - Fetched data for HDFCBANK (2477 rows).
2026-01-22 09:48:58,129 - INFO - Fetched data for NAVINFLUOR (2477 rows).
2026-01-22 09:48:58,551 - INFO - Fetched data for SBICARD (1455 rows).
2026-01-22 09:48:59,011 - INFO - Fetched data for SRF (2477 rows).
2026-01-22 09:48:59,460 - INFO - Fetched data for AAVAS (1809 rows).
2026-01-22 09:49:00,757 - INFO - Fetched data for AMBER (1978 rows).
2026-01-22 09:49:01,237 - INFO - Fetched data for KOTAKBANK (2477 rows).
2026-01-22 09:49:01,650 - INFO - Fetched data for MAZDOCK (1312 rows).
2026-01-22 09:49:02,197 - INFO - Fetched data for CHAMBLFERT (2477 rows).
2026-01-22 09:49:02,659 - INFO - Fetched data for ICICIBANK (2477 rows).
2026-01-22 09:49:03,139 - INFO - Fetched data for INDIGO (2477 rows).
2026-01-22 09:49:03,652 - INFO - Fetched data for MANAPPURAM (2477 rows).
2026-01-22 09:49:04,101 - INFO - Fetched data for REDINGTON (2477 rows).
2026-01-22 09:49:04,569 - INFO - Fetched data for SOLARINDS (2477 rows).
2026-01-22 09:49:05,042 - INFO - Fetched data for TATACONSUM (2476 rows).
2026-01-22 09:49:05,485 - INFO - Fetched data for APLAPOLLO (2477 rows).
2026-01-22 09:49:05,928 - INFO - Fetched data for BAJAJHLDNG (2477 rows).
2026-01-22 09:49:06,300 - INFO - Fetched data for BHARTIHEXA (443 rows).
2026-01-22 09:49:06,739 - INFO - Fetched data for IGL (2477 rows).
2026-01-22 09:49:07,178 - INFO - Fetched data for MFSL (2477 rows).
2026-01-22 09:49:07,601 - INFO - Fetched data for AUBANK (2118 rows).
2026-01-22 09:49:08,032 - INFO - Fetched data for BERGEPAINT (2477 rows).
2026-01-22 09:49:08,481 - INFO - Fetched data for BHARTIARTL (2477 rows).
2026-01-22 09:49:08,926 - INFO - Fetched data for CUB (2477 rows).
2026-01-22 09:49:09,380 - INFO - Fetched data for ENGINERSIN (2477 rows).
2026-01-22 09:49:09,844 - INFO - Fetched data for HDFCLIFE (2028 rows).
2026-01-22 09:49:10,300 - INFO - Fetched data for NH (2477 rows).
2026-01-22 09:49:10,743 - INFO - Fetched data for POONAWALLA (2477 rows).
2026-01-22 09:49:11,276 - INFO - Fetched data for GLAND (1282 rows).
2026-01-22 09:49:11,710 - INFO - Fetched data for HEG (2477 rows).
2026-01-22 09:49:12,146 - INFO - Fetched data for IIFL (2477 rows).
2026-01-22 09:49:12,636 - INFO - Fetched data for JKCEMENT (2477 rows).
2026-01-22 09:49:13,024 - INFO - Fetched data for SYRMA (846 rows).
2026-01-22 09:49:13,479 - INFO - Fetched data for BEML (2477 rows).
2026-01-22 09:49:13,892 - INFO - Fetched data for DATAPATTNS (1013 rows).
2026-01-22 09:49:14,300 - INFO - Fetched data for DELHIVERY (912 rows).
2026-01-22 09:49:14,760 - INFO - Fetched data for INTELLECT (2477 rows).
2026-01-22 09:49:15,167 - INFO - Fetched data for NYKAA (1044 rows).
2026-01-22 09:49:15,625 - INFO - Fetched data for HEROMOTOCO (2477 rows).
2026-01-22 09:49:16,081 - INFO - Fetched data for HINDCOPPER (2477 rows).
2026-01-22 09:49:16,461 - INFO - Fetched data for HYUNDAI (312 rows).
2026-01-22 09:49:16,874 - INFO - Fetched data for NETWEB (619 rows).
2026-01-22 09:49:17,322 - INFO - Fetched data for HINDALCO (2477 rows).
2026-01-22 09:49:17,767 - INFO - Fetched data for INDIANB (2477 rows).
2026-01-22 09:49:18,229 - INFO - Fetched data for EICHERMOT (2477 rows).
2026-01-22 09:49:18,675 - INFO - Fetched data for LTIM (2357 rows).
2026-01-22 09:49:19,135 - INFO - Fetched data for M&MFIN (2477 rows).
2026-01-22 09:49:19,587 - INFO - Fetched data for MARUTI (2477 rows).
2026-01-22 09:49:20,031 - INFO - Fetched data for JKTYRE (2477 rows).
2026-01-22 09:49:20,470 - INFO - Fetched data for RADICO (2477 rows).
2026-01-22 09:49:20,927 - INFO - Fetched data for SBIN (2477 rows).
2026-01-22 09:49:21,372 - INFO - Fetched data for SHRIRAMFIN (2477 rows).
(2026-01-22 09:49:21,775) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:21,775) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
2026-01-22 09:49:21,775 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-22 09:49:22,101 - INFO - Fetched data for GOLDBEES (2474 rows).

Processing: 2023-04
Last Month Value: {}
            Date    Open    High     Low   Close   volume  oi     Ticker  \
1384  2023-04-03  154.00  154.90  152.00  153.80  2347046   0  ABCAPITAL
1385  2023-04-05  153.80  156.45  152.80  155.25  3010848   0  ABCAPITAL
1386  2023-04-06  155.70  159.30  153.80  157.90  3718974   0  ABCAPITAL
1387  2023-04-10  158.75  160.30  155.90  159.75  3508046   0  ABCAPITAL
1388  2023-04-11  160.50  161.30  157.05  157.60  2936298   0  ABCAPITAL
...          ...     ...     ...     ...     ...      ...  ..        ...
45314 2023-04-24  332.50  336.80  324.45  331.60   867129   0   TITAGARH
45315 2023-04-25  330.00  352.90  329.05  336.85  4114109   0   TITAGARH
45316 2023-04-26  339.00  342.70  329.15  332.35   709013   0   TITAGARH
45317 2023-04-27  332.85  339.55  323.95  331.50   794444   0   TITAGARH
45318 2023-04-28  333.00  335.20  329.25  332.25   351839   0   TITAGARH

        %change
1384   0.001628
1385   0.009428
1386   0.017069
1387   0.011716
1388  -0.013459
...         ...
45314 -0.003456
45315  0.015832
45316 -0.013359
45317 -0.002558
45318  0.002262

[340 rows x 9 columns]

Processing: 2023-05
Last Month Value: {'ABCAPITAL': 4.083360468902638, 'ANANDRATHI': 4.009068961247988, 'BANKBARODA': 4.169751258513473, 'BANKINDIA': 4.219691895512391, 'BOSCHLTD': 3.7503775187275097, 'CANBK': 4.184973637961335, 'CUMMINSIND': 3.6258514359352, 'FINCABLES': 4.1297994093034704, 'GODFRYPHLP': 3.6479970326409497, 'J&KBANK': 4.449541284403672, 'JINDALSAW': 4.202364633310487, 'JSL': 3.6477743271221517, 'KAYNES': 3.846009036144577, 'KIRLOSENG': 3.7286985609694505, 'NCC': 4.2342130065975505, 'PFC': 4.197899505766063, 'PNB': 4.204667381974249, 'RKFORGE': 4.272981475008741, 'SHREECEM': 3.4847199654789884, 'TITAGARH': 4.74823742378049}
            Date     Open     High      Low    Close   volume  oi      Ticker  \
1401  2023-05-02   167.95   170.40   167.40   167.95  3831072   0   ABCAPITAL
1402  2023-05-03   168.00   170.35   166.55   169.30  2860885   0   ABCAPITAL
1403  2023-05-04   169.25   173.90   169.00   173.35  4709083   0   ABCAPITAL
1404  2023-05-05   173.25   174.15   170.25   170.65  2663617   0   ABCAPITAL
1405  2023-05-08   171.00   175.30   171.00   174.30  5200785   0   ABCAPITAL
...          ...      ...      ...      ...      ...      ...  ..         ...
66166 2023-05-25  4018.05  4018.05  3950.00  3988.05    13730   0  LINDEINDIA
66167 2023-05-26  4000.00  4014.80  3959.60  3991.40    16124   0  LINDEINDIA
66168 2023-05-29  4028.95  4028.95  3962.00  3977.10    13825   0  LINDEINDIA
66169 2023-05-30  3978.05  3998.00  3950.00  3987.05    12406   0  LINDEINDIA
66170 2023-05-31  3985.00  4006.95  3938.05  3956.20    20105   0  LINDEINDIA

        %change
1401   0.004486
1402   0.008038
1403   0.023922
1404  -0.015575
1405   0.021389
...         ...
66166 -0.002701
66167  0.000840
66168 -0.003583
66169  0.002502
66170 -0.007738

[440 rows x 9 columns]

Processing: 2023-06
Last Month Value: {'ABCAPITAL': 4.159068707261478, 'ANANDRATHI': 3.9932833973009774, 'ANANTRAJ': 4.204195550168963, 'BANKBARODA': 4.108676339946698, 'CYIENT': 4.306628051800918, 'FINCABLES': 3.6962373861678577, 'GLENMARK': 4.153592997806519, 'HINDPETRO': 4.066018579465235, 'IRCON': 4.276214162011375, 'J&KBANK': 4.3960244648318065, 'JBMA': 3.940618850495107, 'JINDALSAW': 6.250856751199449, 'JSL': 3.7998188405797078, 'JWL': 4.888945389668849, 'KIRLOSENG': 3.8342590254986106, 'KPITTECH': 4.5398219911957165, 'LINDEINDIA': 3.8874927703312947, 'NCC': 4.2147737983034865, 'PFC': 4.506795716639211, 'TITAGARH': 5.04049161585366}
            Date    Open    High     Low   Close   volume  oi      Ticker  \
2444  2023-06-01  430.00  430.05  424.25  425.70    43702   0  ANANDRATHI
2445  2023-06-02  427.35  431.00  425.70  428.40    44020   0  ANANDRATHI
2446  2023-06-05  429.50  429.50  424.05  425.15    39320   0  ANANDRATHI
2447  2023-06-06  422.55  429.15  422.55  426.60    42438   0  ANANDRATHI
2448  2023-06-07  428.25  432.55  426.75  430.15   132068   0  ANANDRATHI
...          ...     ...     ...     ...     ...      ...  ..         ...
88934 2023-06-23  322.00  322.30  305.45  306.45  9995718   0         VBL
88935 2023-06-26  307.55  320.40  302.00  319.70  6203205   0         VBL
88936 2023-06-27  322.75  325.00  318.40  319.75  5459653   0         VBL
88937 2023-06-28  322.30  322.50  315.60  317.40  4741040   0         VBL
88938 2023-06-30  318.80  323.15  312.40  321.00  6921218   0         VBL

        %change
2444  -0.010115
2445   0.006342
2446  -0.007586
2447   0.003411
2448   0.008322
...         ...
88934 -0.046515
88935  0.043237
88936  0.000156
88937 -0.007349
88938  0.011342

[420 rows x 9 columns]

Processing: 2023-07
Last Month Value: {'ABB': 4.486223996375564, 'ANANDRATHI': 4.020675993561966, 'ANANTRAJ': 4.903742721620947, 'APARINDS': 5.224866575585293, 'CHENNPETRO': 4.32025056102682, 'CHOLAFIN': 4.547654099302683, 'GLENMARK': 4.69732976414422, 'GRAVITA': 4.129092383374049, 'ITC': 4.242129205692896, 'JINDALSAW': 6.57727895819054, 'JSL': 4.275362318840579, 'JWL': 6.471429617094031, 'KAYNES': 4.403378797329659, 'KPITTECH': 4.654059551295888, 'NCC': 4.31550424128181, 'POLYCAB': 4.340916153889717, 'POWERINDIA': 4.52367544441997, 'RAMCOCEM': 4.278146992476656, 'RKFORGE': 4.793341568058353, 'VBL': 3.963840547892039}
             Date      Open      High       Low     Close  volume  oi  \
14850  2023-07-03   1947.00   1953.50   1885.10   1889.95  573439   0
14851  2023-07-04   1894.50   1930.00   1851.75   1856.65  721898   0
14852  2023-07-05   1865.00   1884.90   1852.70   1874.65  839386   0
14853  2023-07-06   1887.60   1920.00   1869.00   1916.00  823919   0
14854  2023-07-07   1915.95   1922.80   1893.00   1902.35  407591   0
...           ...       ...       ...       ...       ...     ...  ..
109717 2023-07-25  12141.75  12141.75  11818.05  11989.65    4857   0
109718 2023-07-26  12013.80  12119.90  11870.00  11978.15    5073   0
109719 2023-07-27  11981.00  12350.45  11684.05  11990.20   42132   0
109720 2023-07-28  12082.15  12489.00  11865.55  12395.70   27141   0
109721 2023-07-31  12550.00  13100.00  12364.30  12954.45    9178   0

            Ticker   %change
14850   CUMMINSIND -0.027353
14851   CUMMINSIND -0.017620
14852   CUMMINSIND  0.009695
14853   CUMMINSIND  0.022057
14854   CUMMINSIND -0.007124
...            ...       ...
109717   ZFCVINDIA -0.005446
109718   ZFCVINDIA -0.000959
109719   ZFCVINDIA  0.001006
109720   ZFCVINDIA  0.033819
109721   ZFCVINDIA  0.045076

[420 rows x 9 columns]

Processing: 2023-08
Last Month Value: {'ABB': 4.617879405538928, 'ANANTRAJ': 5.575639807244792, 'AUROPHARMA': 5.173134907233746, 'CHENNPETRO': 4.494620441826486, 'CHOLAFIN': 4.508230477951457, 'CUMMINSIND': 4.635071181568218, 'CYIENT': 4.473468653216369, 'ELECON': 5.9333155370549155, 'EXIDEIND': 4.825470760219699, 'GLENMARK': 5.4745432761553605, 'ITC': 4.374555724729902, 'JINDALSAW': 8.33790267306374, 'KAYNES': 5.3047347003435625, 'KPITTECH': 4.623952082185378, 'LTF': 4.726582727437164, 'MAHSEAMLES': 5.134697998338808, 'RECLTD': 5.640540032693313, 'SIEMENS': 4.839210744973659, 'ZENSARTECH': 5.882261063436055, 'ZFCVINDIA': 4.874064550189812}
             Date    Open    High     Low   Close   volume  oi      Ticker  \
2486   2023-08-01  584.50  637.45  584.45  627.80   366400   0  ANANDRATHI
2487   2023-08-02  625.00  633.50  606.20  617.55   227104   0  ANANDRATHI
2488   2023-08-03  617.95  627.50  610.35  618.25    85620   0  ANANDRATHI
2489   2023-08-04  624.50  647.15  620.05  644.10   320332   0  ANANDRATHI
2490   2023-08-07  649.00  659.40  628.60  645.65   208518   0  ANANDRATHI
...           ...     ...     ...     ...     ...      ...  ..         ...
119647 2023-08-25  349.35  351.70  345.60  347.70   364485   0    USHAMART
119648 2023-08-28  347.00  351.10  344.30  348.45   354963   0    USHAMART
119649 2023-08-29  348.45  358.00  345.00  348.65  1464308   0    USHAMART
119650 2023-08-30  349.70  351.80  341.15  345.20   766855   0    USHAMART
119651 2023-08-31  345.20  357.00  344.20  355.00   626334   0    USHAMART

         %change
2486    0.079250
2487   -0.016327
2488    0.001134
2489    0.041812
2490    0.002406
...          ...
119647 -0.007989
119648  0.002157
119649  0.000574
119650 -0.009895
119651  0.028389

[440 rows x 9 columns]

Processing: 2023-09
Last Month Value: {'ABB': 4.444181494759071, 'ADANIPORTS': 4.723077084547537, 'ANANDRATHI': 5.686286901035008, 'ANANTRAJ': 6.069193839277126, 'AUROPHARMA': 5.221893551844341, 'ELECON': 6.915413964122872, 'GLENMARK': 5.32862031010946, 'JINDALSAW': 9.00102810143934, 'KAYNES': 5.891793372207559, 'MAHSEAMLES': 5.165919267739371, 'NCC': 4.9560419392520245, 'NEULANDLAB': 5.179214547048895, 'PFC': 4.616453166769804, 'POLYCAB': 4.932374365682748, 'RECLTD': 6.632741457512981, 'RKFORGE': 5.877134168017744, 'SARDAEN': 5.089095190978605, 'TITAGARH': 5.782506693313642, 'USHAMART': 4.877986876215064, 'ZENSARTECH': 6.231719878121494}
             Date    Open    High     Low   Close  volume  oi      Ticker  \
2508   2023-09-01  702.65  720.40  696.00  699.40  156460   0  ANANDRATHI
2509   2023-09-04  705.50  705.50  696.50  700.10  134648   0  ANANDRATHI
2510   2023-09-05  704.90  715.00  685.00  696.95  169064   0  ANANDRATHI
2511   2023-09-06  696.50  696.50  685.00  689.95  720050   0  ANANDRATHI
2512   2023-09-07  689.95  699.30  687.55  691.55  133304   0  ANANDRATHI
...           ...     ...     ...     ...     ...     ...  ..         ...
131833 2023-09-25  850.00  855.25  842.05  848.50  191384   0  NATCOPHARM
131834 2023-09-26  853.00  878.70  850.75  871.60  415943   0  NATCOPHARM
131835 2023-09-27  871.60  888.00  871.60  878.90  347269   0  NATCOPHARM
131836 2023-09-28  886.20  898.70  868.05  872.95  397481   0  NATCOPHARM
131837 2023-09-29  877.65  896.50  870.10  873.05  417250   0  NATCOPHARM

         %change
2508   -0.019418
2509    0.001001
2510   -0.004499
2511   -0.010044
2512    0.002319
...          ...
131833 -0.000765
131834  0.027225
131835  0.008375
131836 -0.006770
131837  0.000115

[400 rows x 9 columns]

Processing: 2023-10
Last Month Value: {'ANANDRATHI': 6.699972676662913, 'ANANTRAJ': 6.071958847859939, 'ANGELONE': 4.9664376036099265, 'APARINDS': 5.487954079010068, 'BSE': 6.128501684341043, 'ELECON': 6.056273633585749, 'GLENMARK': 5.944623688203222, 'HBLENGINE': 4.994571482524582, 'JINDALSAW': 8.908498971898563, 'KALYANKJIL': 4.534700144103211, 'KAYNES': 6.728505545036138, 'LUPIN': 5.353453790798162, 'MAHSEAMLES': 5.900339589484932, 'NATCOPHARM': 4.794979102652155, 'NEULANDLAB': 4.924021965453982, 'RECLTD': 7.987638361153279, 'RKFORGE': 5.304086808722027, 'SARDAEN': 5.06266728639687, 'TITAGARH': 5.542561281253229, 'USHAMART': 4.724089825472504}
             Date    Open    High     Low   Close   volume  oi      Ticker  \
2528   2023-10-03  844.65  880.00  826.00  868.00   255026   0  ANANDRATHI
2529   2023-10-04  868.95  899.95  856.05  888.95   420352   0  ANANDRATHI
2530   2023-10-05  891.90  892.85  881.05  887.55   175190   0  ANANDRATHI
2531   2023-10-06  903.50  917.45  885.50  909.80   220828   0  ANANDRATHI
2532   2023-10-09  909.00  986.00  882.15  945.05   846110   0  ANANDRATHI
...           ...     ...     ...     ...     ...      ...  ..         ...
146948 2023-10-25  314.45  317.75  296.20  302.20  1634990   0  TATAINVEST
146949 2023-10-26  300.30  307.00  288.50  304.20  1535160   0  TATAINVEST
146950 2023-10-27  306.40  317.00  306.00  311.25  1273610   0  TATAINVEST
146951 2023-10-30  314.00  316.40  305.15  306.80   650070   0  TATAINVEST
146952 2023-10-31  309.40  317.00  308.50  310.60   997030   0  TATAINVEST

         %change
2528    0.032842
2529    0.024136
2530   -0.001575
2531    0.025069
2532    0.038745
...          ...
146948 -0.035429
146949  0.006618
146950  0.023176
146951 -0.014297
146952  0.012386

[400 rows x 9 columns]

Processing: 2023-11
Last Month Value: {'ANANDRATHI': 7.610017751676091, 'APARINDS': 5.18928786675223, 'BSE': 8.796485718192045, 'CHOLAHLDNG': 5.654917665730307, 'ETERNAL': 5.969951617203702, 'GLENMARK': 5.195899898134375, 'HBLENGINE': 5.525092657232609, 'HUDCO': 4.726046177439652, 'KALYANKJIL': 5.7533198488358455, 'KAYNES': 6.971577670755608, 'LUPIN': 5.156455832733359, 'PFC': 5.644156437089418, 'POLYCAB': 5.31123273283108, 'RBLBANK': 5.028669305659604, 'RECLTD': 7.993196912552832, 'RKFORGE': 5.274425119383932, 'SARDAEN': 4.667397757000473, 'SUZLON': 6.838106464818658, 'TARIL': 5.673120896106732, 'TATAINVEST': 5.470452404353735}
             Date     Open     High      Low    Close   volume  oi  \
2548   2023-11-01   954.55  1038.55   954.55  1012.15   430786   0
2549   2023-11-02  1050.00  1050.00   988.50   994.85   149450   0
2550   2023-11-03  1014.40  1024.00   982.60  1012.30   128044   0
2551   2023-11-06  1024.90  1050.00  1015.60  1024.20   113630   0
2552   2023-11-07  1039.50  1039.50  1015.50  1024.05    52786   0
...           ...      ...      ...      ...      ...      ...  ..
158947 2023-11-23  4100.00  4130.00  4080.05  4111.05    56111   0
158948 2023-11-24  4055.05  4165.20  4036.00  4129.25   143208   0
158949 2023-11-28  4149.95  4191.20  4074.05  4123.25   235636   0
158950 2023-11-29  4140.00  4237.00  4100.00  4121.30   180837   0
158951 2023-11-30  4109.80  4593.90  4089.00  4431.15  1282443   0

            Ticker   %change
2548    ANANDRATHI  0.060343
2549    ANANDRATHI -0.017092
2550    ANANDRATHI  0.017540
2551    ANANDRATHI  0.011755
2552    ANANDRATHI -0.000146
...            ...       ...
158947  SUPREMEIND  0.007697
158948  SUPREMEIND  0.004427
158949  SUPREMEIND -0.001453
158950  SUPREMEIND -0.000473
158951  SUPREMEIND  0.075183

[420 rows x 9 columns]

Processing: 2023-12
Last Month Value: {'ANANDRATHI': 10.346132247904928, 'ANGELONE': 6.366196680200352, 'APARINDS': 5.592001332089489, 'BSE': 11.695359795853884, 'BSOFT': 6.16818469832359, 'CHOLAHLDNG': 4.87812415225558, 'DIXON': 5.788568651935923, 'GRAVITA': 6.023453461884396, 'JINDALSAW': 5.622710155101336, 'KALYANKJIL': 6.478712444948159, 'KAYNES': 7.214942302041528, 'KIRLOSBROS': 5.821134552880705, 'LUPIN': 5.854633050700846, 'MRPL': 6.2684584127196645, 'RECLTD': 9.691334365115344, 'RKFORGE': 6.595194230744151, 'SARDAEN': 5.506196467638176, 'SUPREMEIND': 5.485073993043459, 'SUZLON': 9.106301909848375, 'TARIL': 6.186874963644066}
             Date     Open     High      Low    Close    volume  oi  \
2569   2023-12-01  1350.00  1350.00  1262.60  1298.50    120996   0
2570   2023-12-04  1342.40  1356.00  1308.00  1333.80    103846   0
2571   2023-12-05  1346.45  1346.45  1302.55  1313.15     96794   0
2572   2023-12-06  1315.00  1324.20  1280.00  1298.95     87580   0
2573   2023-12-07  1309.95  1309.95  1282.50  1290.70     53376   0
...           ...      ...      ...      ...      ...       ...  ..
174405 2023-12-22    90.85    90.90    88.20    89.70  19350518   0
174406 2023-12-26    90.05    92.70    89.25    91.55  18112291   0
174407 2023-12-27    94.60    95.60    92.35    92.90  30200399   0
174408 2023-12-28    93.30    93.35    90.90    91.30  16418489   0
174409 2023-12-29    91.70    92.40    90.60    90.95  14891333   0

            Ticker   %change
2569    ANANDRATHI  0.000578
2570    ANANDRATHI  0.027185
2571    ANANDRATHI -0.015482
2572    ANANDRATHI -0.010814
2573    ANANDRATHI -0.006351
...            ...       ...
174405        SJVN -0.002779
174406        SJVN  0.020624
174407        SJVN  0.014746
174408        SJVN -0.017223
174409        SJVN -0.003834

[400 rows x 9 columns]

Processing: 2024-01
Last Month Value: {'ANANDRATHI': 10.338957122477753, 'ANGELONE': 7.239064563111184, 'APARINDS': 6.064897850659422, 'BHEL': 6.704551558509593, 'BSE': 10.48779070168984, 'GPIL': 6.506198756641542, 'KALYANKJIL': 7.056635117674997, 'MAHSEAMLES': 5.616951555275957, 'MCX': 5.912685361608677, 'MRPL': 6.880834605553364, 'NLCINDIA': 8.784635022242506, 'PFC': 6.745332819659913, 'PRESTIGE': 6.940534241555239, 'RECLTD': 11.474239726520992, 'RKFORGE': 5.979302209071187, 'SARDAEN': 5.819884204630087, 'SIGNATURE': 6.814258113528315, 'SJVN': 6.321394365327545, 'SUZLON': 8.536459704446822, 'TATAINVEST': 5.96637459167237}
             Date     Open     High      Low    Close   volume  oi  \
2589   2024-01-01  1307.00  1319.00  1273.00  1283.70   131032   0
2590   2024-01-02  1287.50  1315.50  1255.05  1289.30   130004   0
2591   2024-01-03  1285.00  1312.50  1281.75  1299.25    86768   0
2592   2024-01-04  1292.55  1398.95  1292.55  1333.70   381556   0
2593   2024-01-05  1338.20  1383.40  1338.20  1350.40   171800   0
...           ...      ...      ...      ...      ...      ...  ..
186085 2024-01-24  3164.10  3241.30  3130.00  3222.75   339968   0
186086 2024-01-25  3223.05  3252.50  3180.00  3231.80   489321   0
186087 2024-01-29  3248.00  3295.00  3225.60  3246.40   604096   0
186088 2024-01-30  3263.00  3275.00  3029.05  3054.95  1206541   0
186089 2024-01-31  3054.00  3104.50  2992.30  3086.95   986931   0

            Ticker   %change
2589    ANANDRATHI -0.010140
2590    ANANDRATHI  0.004362
2591    ANANDRATHI  0.007717
2592    ANANDRATHI  0.026515
2593    ANANDRATHI  0.012522
...            ...       ...
186085       TRENT  0.018520
186086       TRENT  0.002808
186087       TRENT  0.004518
186088       TRENT -0.058973
186089       TRENT  0.010475

[440 rows x 9 columns]

Processing: 2024-02
Last Month Value: {'ANANDRATHI': 12.190936718847095, 'ANGELONE': 6.81887171352065, 'BHEL': 7.90655589372159, 'BSE': 10.971526591023599, 'BSOFT': 7.319814922828004, 'DBREALTY': 8.464642652937679, 'GVT&D': 8.427326982683388, 'IREDA': 11.001198266661966, 'KALYANKJIL': 6.978914482377253, 'MAHSEAMLES': 6.391190676554878, 'MRPL': 9.149468771409856, 'NBCC': 9.877578157953224, 'NLCINDIA': 8.98739736148148, 'PFC': 7.814607350533861, 'RAILTEL': 8.051020789541003, 'RECLTD': 13.869975379727022, 'SIGNATURE': 8.891894228384217, 'SUZLON': 10.268333073804492, 'TATAINVEST': 7.852289586961617, 'TRENT': 6.285860173616012}
             Date     Open     High      Low    Close   volume  oi  \
2611   2024-02-01  1544.00  1625.00  1535.00  1606.95   220708   0
2612   2024-02-02  1637.00  1665.00  1615.00  1642.85   130296   0
2613   2024-02-05  1656.50  1748.00  1595.05  1734.95   180660   0
2614   2024-02-06  1760.00  1774.00  1658.50  1698.95   154892   0
2615   2024-02-07  1700.05  1749.85  1700.05  1726.30    87212   0
...           ...      ...      ...      ...      ...      ...  ..
188583 2024-02-23   415.25   419.80   411.00   414.50  1634815   0
188584 2024-02-26   410.00   414.90   402.95   404.40  1245336   0
188585 2024-02-27   404.00   413.00   399.05   402.00  1528795   0
188586 2024-02-28   402.00   406.70   390.00   391.40  1445705   0
188587 2024-02-29   390.45   396.00   382.80   389.90  1240085   0

            Ticker   %change
2611    ANANDRATHI  0.050878
2612    ANANDRATHI  0.022340
2613    ANANDRATHI  0.056061
2614    ANANDRATHI -0.020750
2615    ANANDRATHI  0.016098
...            ...       ...
188583     GMDCLTD -0.002527
188584     GMDCLTD -0.024367
188585     GMDCLTD -0.005935
188586     GMDCLTD -0.026368
188587     GMDCLTD -0.003832

[420 rows x 9 columns]

Processing: 2024-03
Last Month Value: {'ANANDRATHI': 14.576665923382293, 'ANGELONE': 5.775602087209556, 'BHEL': 7.882307967651031, 'BSE': 11.175503071445444, 'BSOFT': 6.695631282464272, 'DBREALTY': 8.987503177134185, 'GMDCLTD': 6.0467692693907225, 'GVT&D': 11.263624889305817, 'IREDA': 9.079921891708624, 'KALYANKJIL': 7.908572850746468, 'MRPL': 11.77209255084533, 'NBCC': 10.318234889217647, 'NLCINDIA': 7.710167925420577, 'PRESTIGE': 6.54916028453682, 'RAILTEL': 8.262671810411323, 'RECLTD': 12.285788230855292, 'SIGNATURE': 10.664292588795867, 'SUZLON': 10.111905801733474, 'TATAINVEST': 10.145066184485406, 'TRENT': 7.904388481168347}
             Date     Open     High      Low    Close   volume  oi  \
2632   2024-03-01  1849.50  1865.50  1841.00  1854.95    86788   0

In [7]:
final_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
0,2023-04-03,154.00,154.90,152.00,153.80,2347046,0,ABCAPITAL,0.001628,3.756106,75.779854
1,2023-04-03,407.00,410.95,403.05,405.15,112564,0,ANANDRATHI,0.003219,3.762071,75.779854
2,2023-04-03,169.10,170.25,168.10,169.20,16659059,0,BANKBARODA,0.002073,3.757773,75.779854
3,2023-04-03,75.00,76.45,74.10,75.95,8102076,0,BANKINDIA,0.017415,3.815305,75.779854
4,2023-04-03,19500.00,19500.85,19200.00,19434.25,29923,0,BOSCHLTD,0.003322,3.762458,75.779854
...,...,...,...,...,...,...,...,...,...,...,...
14632,2026-01-22,242.60,248.20,242.50,246.90,400919,0,NYKAA,0.021726,9.589283,216.321481
14633,2026-01-22,2849.20,2881.50,2700.00,2869.30,68639,0,RADICO,0.013028,9.138293,216.321481
14634,2026-01-22,1035.00,1055.50,1034.05,1049.00,3197476,0,SBIN,0.019783,11.219358,216.321481
14635,2026-01-22,995.05,1005.40,986.10,1002.90,759014,0,SHRIRAMFIN,0.017140,10.575565,216.321481
14636,2026-01-22,680.00,694.00,676.25,688.55,4929573,0,VEDL,0.017587,11.967502,216.321481

In [8]:
old_df = final_df[~((final_df['Date']>'2025-11-30') & (final_df['Ticker']=='GOLDBEES'))]
old_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
0,2023-04-03,154.00,154.90,152.00,153.80,2347046,0,ABCAPITAL,0.001628,3.756106,75.779854
1,2023-04-03,407.00,410.95,403.05,405.15,112564,0,ANANDRATHI,0.003219,3.762071,75.779854
2,2023-04-03,169.10,170.25,168.10,169.20,16659059,0,BANKBARODA,0.002073,3.757773,75.779854
3,2023-04-03,75.00,76.45,74.10,75.95,8102076,0,BANKINDIA,0.017415,3.815305,75.779854
4,2023-04-03,19500.00,19500.85,19200.00,19434.25,29923,0,BOSCHLTD,0.003322,3.762458,75.779854
...,...,...,...,...,...,...,...,...,...,...,...
14632,2026-01-22,242.60,248.20,242.50,246.90,400919,0,NYKAA,0.021726,9.589283,216.321481
14633,2026-01-22,2849.20,2881.50,2700.00,2869.30,68639,0,RADICO,0.013028,9.138293,216.321481
14634,2026-01-22,1035.00,1055.50,1034.05,1049.00,3197476,0,SBIN,0.019783,11.219358,216.321481
14635,2026-01-22,995.05,1005.40,986.10,1002.90,759014,0,SHRIRAMFIN,0.017140,10.575565,216.321481
14636,2026-01-22,680.00,694.00,676.25,688.55,4929573,0,VEDL,0.017587,11.967502,216.321481

In [9]:
np.sort(old_df['Ticker'].unique())

array(['AAVAS', 'ABB', 'ABCAPITAL', 'ADANIPORTS', 'AIIL', 'AJANTPHARM',
       'AMBER', 'ANANDRATHI', 'ANANTRAJ', 'ANGELONE', 'APARINDS',
       'APLAPOLLO', 'ASTERDM', 'AUBANK', 'AUROPHARMA', 'BAJAJ-AUTO',
       'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BANKINDIA', 'BASF',
       'BDL', 'BEL', 'BEML', 'BERGEPAINT', 'BHARTIARTL', 'BHARTIHEXA',
       'BHEL', 'BLUESTARCO', 'BOSCHLTD', 'BPCL', 'BSE', 'BSOFT', 'CANBK',
       'CHAMBLFERT', 'CHENNPETRO', 'CHOLAFIN', 'CHOLAHLDNG', 'COCHINSHIP',
       'COFORGE', 'COHANCE', 'COLPAL', 'CONCORDBIO', 'COROMANDEL', 'CUB',
       'CUMMINSIND', 'CYIENT', 'DATAPATTNS', 'DBREALTY', 'DEEPAKFERT',
       'DELHIVERY', 'DIVISLAB', 'DIXON', 'DLF', 'DOMS', 'ECLERX',
       'EICHERMOT', 'EIHOTEL', 'ELECON', 'EMAMILTD', 'ENGINERSIN', 'ERIS',
       'ETERNAL', 'EXIDEIND', 'FINCABLES', 'FLUOROCHEM', 'FORTIS',
       'GLAND', 'GLENMARK', 'GMDCLTD', 'GODFRYPHLP', 'GODREJPROP',
       'GOLDBEES', 'GPIL', 'GRAVITA', 'GVT&D', 'HAL', 'HBLENGINE',
       'HDFCBANK', 'HDFCLIFE', 'HEG', 'HEROMOTOCO', 'HINDALCO',
       'HINDCOPPER', 'HINDPETRO', 'HSCL', 'HUDCO', 'HYUNDAI', 'ICICIBANK',
       'IGL', 'IIFL', 'INDHOTEL', 'INDIANB', 'INDIGO', 'INDUSTOWER',
       'INOXWIND', 'INTELLECT', 'IOC', 'IPCALAB', 'IRCON', 'IREDA', 'ITC',
       'J&KBANK', 'JBMA', 'JINDALSAW', 'JKCEMENT', 'JKTYRE', 'JMFINANCIL',
       'JSL', 'JSWENERGY', 'JSWHL', 'JWL', 'KALYANKJIL', 'KAYNES',
       'KFINTECH', 'KIMS', 'KIRLOSBROS', 'KIRLOSENG', 'KOTAKBANK',
       'KPITTECH', 'LAURUSLABS', 'LINDEINDIA', 'LLOYDSME', 'LTF',
       'LTFOODS', 'LTIM', 'LUPIN', 'M&M', 'M&MFIN', 'MAHSEAMLES',
       'MANAPPURAM', 'MARUTI', 'MAZDOCK', 'MCX', 'MFSL', 'MOTHERSON',
       'MOTILALOFS', 'MRPL', 'MUTHOOTFIN', 'NATCOPHARM', 'NATIONALUM',
       'NAVA', 'NAVINFLUOR', 'NBCC', 'NCC', 'NETWEB', 'NEULANDLAB', 'NH',
       'NHPC', 'NIACL', 'NLCINDIA', 'NYKAA', 'OFSS', 'OIL', 'PAYTM',
       'PCBL', 'PEL', 'PERSISTENT', 'PFC', 'PGEL', 'PNB', 'POLYCAB',
       'POONAWALLA', 'POWERINDIA', 'PPLPHARMA', 'PRESTIGE', 'RADICO',
       'RAILTEL', 'RAMCOCEM', 'RBLBANK', 'RECLTD', 'REDINGTON', 'RKFORGE',
       'RVNL', 'SAGILITY', 'SAIL', 'SARDAEN', 'SBICARD', 'SBIN',
       'SCHNEIDER', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SIGNATURE',
       'SJVN', 'SOLARINDS', 'SRF', 'SUPREMEIND', 'SUZLON', 'SYRMA',
       'TARIL', 'TATACONSUM', 'TATAINVEST', 'TECHNOE', 'THERMAX',
       'TITAGARH', 'TRENT', 'USHAMART', 'VBL', 'VEDL', 'VOLTAS',
       'WELCORP', 'WOCKPHARMA', 'ZENSARTECH', 'ZENTEC', 'ZFCVINDIA',
       'ZYDUSLIFE'], dtype=object)

In [10]:
df = fetch_truedata_history(
    ticker_list = ['GOLDBEES', 'SILVERBEES', 'MOGSEC'],
    duration = '5 Y',
    bar_size = 'EOD',
    sleep_time= 0.1
)[0]
df = df[["Date","Ticker", "Open", "Close"]]
df['%change'] = df['Close'].pct_change()
df = df[df['Date'] >= '2025-12-01']
# df.to_excel('C:\\Users\\Admin\\Momentum\\Automating Momentum True Data\\Trials\\nse200_Nifty_200_2025_Aug_nse200_nse200_nse200_nse200_nse200_returns.xlsx', index=False)
df

(2026-01-22 09:49:24,497) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:24,497) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:24,497) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
2026-01-22 09:49:24,497 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-22 09:49:24,814 - INFO - Fetched data for GOLDBEES (1240 rows).
2026-01-22 09:49:25,232 - INFO - Fetched data for SILVERBEES (983 rows).
2026-01-22 09:49:25,640 - INFO - Fetched data for MOGSEC (1144 rows).

           Date    Ticker    Open   Close   %change
1203 2025-12-01  GOLDBEES  106.09  106.72  0.020073
1204 2025-12-02  GOLDBEES  106.65  105.63 -0.010214
1205 2025-12-03  GOLDBEES  106.25  106.51  0.008331
1206 2025-12-04  GOLDBEES  106.67  105.92 -0.005539
1207 2025-12-05  GOLDBEES  106.27  106.89  0.009158
...         ...       ...     ...     ...       ...
3362 2026-01-14    MOGSEC   62.89   62.99  0.000159
3363 2026-01-16    MOGSEC   62.90   62.70 -0.004604
3364 2026-01-19    MOGSEC   62.39   62.72  0.000319
3365 2026-01-20    MOGSEC   62.61   62.60 -0.001913
3366 2026-01-21    MOGSEC   62.67   62.63  0.000479

[110 rows x 5 columns]

In [11]:
ticker_weights = {'GOLDBEES':0.6, 'SILVERBEES':0.2, 'MOGSEC':0.2}
factor = 51.2140199725867

ticker_value = {ticker: weight * factor for ticker, weight in ticker_weights.items()}
ticker_value

{'GOLDBEES': 30.728411983552018,
 'SILVERBEES': 10.24280399451734,
 'MOGSEC': 10.24280399451734}

In [12]:
df['BaseValue'] = df['Ticker'].map(ticker_value)
# Assign values
df['Value'] = df['Ticker'].map(ticker_value)
# Convert %change to numeric (if needed)
df['%change'] = pd.to_numeric(df['%change'])
# Sort (important for cumprod)
df = df.sort_values(['Ticker', 'Date'])

# Daily growth factor
df['ret_factor'] = 1 + df['%change']

# Cumulative factor per ticker
df['cum_factor'] = df.groupby('Ticker')['ret_factor'].cumprod()

# FINAL DAILY VALUE
df['Value_On_Date'] = df['BaseValue'] * df['cum_factor']

df = df[['Date', 'Ticker', 'Open', 'Close', 'Value_On_Date', '%change']].rename(columns={'Value_On_Date':'Buy_Hold_Value'})
df

           Date      Ticker    Open   Close  Buy_Hold_Value   %change
1203 2025-12-01    GOLDBEES  106.09  106.72       31.345212  0.020073
1204 2025-12-02    GOLDBEES  106.65  105.63       31.025064 -0.010214
1205 2025-12-03    GOLDBEES  106.25  106.51       31.283532  0.008331
1206 2025-12-04    GOLDBEES  106.67  105.92       31.110241 -0.005539
1207 2025-12-05    GOLDBEES  106.27  106.89       31.395144  0.009158
...         ...         ...     ...     ...             ...       ...
2218 2026-01-16  SILVERBEES  262.81  269.44       17.604268  0.025227
2219 2026-01-19  SILVERBEES  274.30  282.95       18.486964  0.050141
2220 2026-01-20  SILVERBEES  288.15  297.62       19.445451  0.051847
2221 2026-01-21  SILVERBEES  300.00  310.68       20.298746  0.043881
2222 2026-01-22  SILVERBEES  299.60  270.61       17.680712 -0.128975

[110 rows x 6 columns]

In [13]:
conc_df = pd.concat([old_df, df])
conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
0,2023-04-03,154.00,154.90,152.00,153.80,2347046.0,0.0,ABCAPITAL,0.001628,3.756106,75.779854
1,2023-04-03,407.00,410.95,403.05,405.15,112564.0,0.0,ANANDRATHI,0.003219,3.762071,75.779854
2,2023-04-03,169.10,170.25,168.10,169.20,16659059.0,0.0,BANKBARODA,0.002073,3.757773,75.779854
3,2023-04-03,75.00,76.45,74.10,75.95,8102076.0,0.0,BANKINDIA,0.017415,3.815305,75.779854
4,2023-04-03,19500.00,19500.85,19200.00,19434.25,29923.0,0.0,BOSCHLTD,0.003322,3.762458,75.779854
...,...,...,...,...,...,...,...,...,...,...,...
2218,2026-01-16,262.81,NaN,NaN,269.44,NaN,NaN,SILVERBEES,0.025227,17.604268,NaN
2219,2026-01-19,274.30,NaN,NaN,282.95,NaN,NaN,SILVERBEES,0.050141,18.486964,NaN
2220,2026-01-20,288.15,NaN,NaN,297.62,NaN,NaN,SILVERBEES,0.051847,19.445451,NaN
2221,2026-01-21,300.00,NaN,NaN,310.68,NaN,NaN,SILVERBEES,0.043881,20.298746,NaN
2222,2026-01-22,299.60,NaN,NaN,270.61,NaN,NaN,SILVERBEES,-0.128975,17.680712,NaN

In [14]:
import plotly.express as px

# ✅ Group by Date and calculate total portfolio value
portfolio_summary = (
    conc_df.groupby("Date", as_index=False)["Buy_Hold_Value"].sum()
)
# ✅ Plot with Plotly
fig = px.line(
    portfolio_summary,
    x="Date",
    y="Buy_Hold_Value",
    title="Buy_Hold_Value Over Time",
    labels={"Date": "Date", "Buy_Hold_Value": "Buy_Hold_Value"},
    markers=True
)

fig.update_traces(line=dict(width=2))
fig.update_layout(width=1000,   # 🔑 width
                  height=500)    # 🔑 height
fig.show()

In [15]:
# Momentum/Automating Momentum True Data/Trials/Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx

In [16]:
conc_df.to_excel('C:\\Users\\anike\\Desktop\\Ocean_dev\\Momentum Handover\\Momentum Handover\\Trials\\Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx', index=False)
# \Trials

In [17]:
nse = fetch_truedata_history(
    ticker_list = ['Nifty 500'],
    duration = '5 Y',
    bar_size = 'EOD',
    sleep_time= 0.1
)[0]
nse = nse[["Date", "Close"]].rename(columns={'Close':'Buy_Hold_Value'})
nse['%change'] = nse['Buy_Hold_Value'].pct_change()
nse = nse[nse['Date'] >= '2023-04-01']
nse.to_excel('Trials\\nse500_Nifty_500_2025_Apr_nse500_nse500_nse500_nse500_nse500_returns.xlsx', index=False)
nse

(2026-01-22 09:49:27,975) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:27,975) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:27,975) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
(2026-01-22 09:49:27,975) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:14848 Thread:20300)
2026-01-22 09:49:27,975 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-22 09:49:28,295 - INFO - Fetched data for Nifty 500 (1241 rows).

           Date  Buy_Hold_Value   %change
544  2023-04-03        14601.95  0.003029
545  2023-04-05        14709.40  0.007359
546  2023-04-06        14759.20  0.003386
547  2023-04-10        14790.55  0.002124
548  2023-04-11        14867.25  0.005186
...         ...             ...       ...
1236 2026-01-16        23485.30  0.000403
1237 2026-01-19        23373.75 -0.004750
1238 2026-01-20        22946.65 -0.018273
1239 2026-01-21        22835.15 -0.004859
1240 2026-01-22        23136.70  0.013206

[697 rows x 3 columns]

In [18]:
conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
0,2023-04-03,154.00,154.90,152.00,153.80,2347046.0,0.0,ABCAPITAL,0.001628,3.756106,75.779854
1,2023-04-03,407.00,410.95,403.05,405.15,112564.0,0.0,ANANDRATHI,0.003219,3.762071,75.779854
2,2023-04-03,169.10,170.25,168.10,169.20,16659059.0,0.0,BANKBARODA,0.002073,3.757773,75.779854
3,2023-04-03,75.00,76.45,74.10,75.95,8102076.0,0.0,BANKINDIA,0.017415,3.815305,75.779854
4,2023-04-03,19500.00,19500.85,19200.00,19434.25,29923.0,0.0,BOSCHLTD,0.003322,3.762458,75.779854
...,...,...,...,...,...,...,...,...,...,...,...
2218,2026-01-16,262.81,NaN,NaN,269.44,NaN,NaN,SILVERBEES,0.025227,17.604268,NaN
2219,2026-01-19,274.30,NaN,NaN,282.95,NaN,NaN,SILVERBEES,0.050141,18.486964,NaN
2220,2026-01-20,288.15,NaN,NaN,297.62,NaN,NaN,SILVERBEES,0.051847,19.445451,NaN
2221,2026-01-21,300.00,NaN,NaN,310.68,NaN,NaN,SILVERBEES,0.043881,20.298746,NaN
2222,2026-01-22,299.60,NaN,NaN,270.61,NaN,NaN,SILVERBEES,-0.128975,17.680712,NaN