In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("Trials\\Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx")
data

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
0,2023-04-03,154.00,154.90,152.00,153.80,2347046.0,0.0,ABCAPITAL,0.001628,3.756106,75.779854
1,2023-04-03,407.00,410.95,403.05,405.15,112564.0,0.0,ANANDRATHI,0.003219,3.762071,75.779854
2,2023-04-03,169.10,170.25,168.10,169.20,16659059.0,0.0,BANKBARODA,0.002073,3.757773,75.779854
3,2023-04-03,75.00,76.45,74.10,75.95,8102076.0,0.0,BANKINDIA,0.017415,3.815305,75.779854
4,2023-04-03,19500.00,19500.85,19200.00,19434.25,29923.0,0.0,BOSCHLTD,0.003322,3.762458,75.779854
...,...,...,...,...,...,...,...,...,...,...,...
14705,2026-01-16,262.81,NaN,NaN,269.44,NaN,NaN,SILVERBEES,0.025227,17.604268,NaN
14706,2026-01-19,274.30,NaN,NaN,282.95,NaN,NaN,SILVERBEES,0.050141,18.486964,NaN
14707,2026-01-20,288.15,NaN,NaN,297.62,NaN,NaN,SILVERBEES,0.051847,19.445451,NaN
14708,2026-01-21,300.00,NaN,NaN,310.68,NaN,NaN,SILVERBEES,0.043881,20.298746,NaN
14709,2026-01-22,299.60,NaN,NaN,270.61,NaN,NaN,SILVERBEES,-0.128975,17.680712,NaN

In [3]:
# max_date_tickers = data[(data['Date'] == '2025-12-31')]
# max_date_tickers
max_date_tickers = data[(data['Date'] == data['Date'].max())]
max_date_tickers

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value
14580,2026-01-22,3068.30,3074.90,3040.00,3060.00,20679.0,0.0,ANANDRATHI,0.002129,10.328054,216.321481
14581,2026-01-22,152.00,155.55,152.00,155.35,4446840.0,0.0,CANBK,0.030446,10.534751,216.321481
14582,2026-01-22,4015.00,4054.50,4013.00,4039.60,42206.0,0.0,CUMMINSIND,0.009723,9.865580,216.321481
14583,2026-01-22,7175.00,7310.00,7162.00,7306.50,59115.0,0.0,EICHERMOT,0.023319,10.754370,216.321481
14584,2026-01-22,244.10,251.60,244.10,251.10,321274.0,0.0,GPIL,0.034398,9.913871,216.321481
14585,2026-01-22,720.95,729.50,720.05,725.35,438691.0,0.0,HBLENGINE,0.028573,8.695863,216.321481
14586,2026-01-22,5593.00,5664.00,5580.00,5659.00,82465.0,0.0,HEROMOTOCO,0.021757,10.991878,216.321481
14587,2026-01-22,945.00,951.40,941.10,950.20,1072924.0,0.0,HINDALCO,0.011712,11.889951,216.321481
14588,2026-01-22,633.80,637.00,611.60,612.20,392030.0,0.0,IIFL,-0.017099,10.534165,216.321481
14589,2026-01-22,513.00,528.95,512.50,528.20,526792.0,0.0,JKTYRE,0.033761,11.037786,216.321481
14590,2026-01-22,764.00,784.00,756.70,778.00,198702.0,0.0,JSL,0.037402,9.738245,216.321481
14591,2026-01-22,1003.00,1021.40,1002.10,1007.40,322819.0,0.0,LAURUSLABS,0.019739,12.035893,216.321481
14592,2026-01-22,288.00,288.80,285.75,286.30,1706136.0,0.0,LTF,0.017594,12.756571,216.321481
14593,2026-01-22,354.95,362.50,353.00,361.35,311626.0,0.0,M&MFIN,0.033462,10.088824,216.321481
14594,2026-01-22,363.00,368.00,361.65,367.25,2471160.0,0.0,NATIONALUM,0.015906,14.665677,216.321481
14595,2026-01-22,242.60,248.20,242.50,246.90,400919.0,0.0,NYKAA,0.021726,9.589283,216.321481
14596,2026-01-22,2849.20,2881.50,2700.00,2869.30,68639.0,0.0,RADICO,0.013028,9.138293,216.321481
14597,2026-01-22,1035.00,1055.50,1034.05,1049.00,3197476.0,0.0,SBIN,0.019783,11.219358,216.321481
14598,2026-01-22,995.05,1005.40,986.10,1002.90,759014.0,0.0,SHRIRAMFIN,0.017140,10.575565,216.321481
14599,2026-01-22,680.00,694.00,676.25,688.55,4929573.0,0.0,VEDL,0.017587,11.967502,216.321481
14636,2026-01-22,131.44,NaN,NaN,123.10,NaN,NaN,GOLDBEES,-0.087945,36.156256,NaN
14709,2026-01-22,299.60,NaN,NaN,270.61,NaN,NaN,SILVERBEES,-0.128975,17.680712,NaN

In [4]:
total_value = max_date_tickers['Buy_Hold_Value'].sum()

# Calculate weights
max_date_tickers['Weight'] = max_date_tickers['Buy_Hold_Value'] / total_value

# Format as percentage (optional)
max_date_tickers['Weight_Percent'] = max_date_tickers['Weight']

max_date_tickers

C:\Users\anike\AppData\Local\Temp\ipykernel_13404\2488948854.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  max_date_tickers['Weight'] = max_date_tickers['Buy_Hold_Value'] / total_value
C:\Users\anike\AppData\Local\Temp\ipykernel_13404\2488948854.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  max_date_tickers['Weight_Percent'] = max_date_tickers['Weight']

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Total_Portfolio_Value,Weight,Weight_Percent
14580,2026-01-22,3068.30,3074.90,3040.00,3060.00,20679.0,0.0,ANANDRATHI,0.002129,10.328054,216.321481,0.038230,0.038230
14581,2026-01-22,152.00,155.55,152.00,155.35,4446840.0,0.0,CANBK,0.030446,10.534751,216.321481,0.038995,0.038995
14582,2026-01-22,4015.00,4054.50,4013.00,4039.60,42206.0,0.0,CUMMINSIND,0.009723,9.865580,216.321481,0.036518,0.036518
14583,2026-01-22,7175.00,7310.00,7162.00,7306.50,59115.0,0.0,EICHERMOT,0.023319,10.754370,216.321481,0.039808,0.039808
14584,2026-01-22,244.10,251.60,244.10,251.10,321274.0,0.0,GPIL,0.034398,9.913871,216.321481,0.036697,0.036697
14585,2026-01-22,720.95,729.50,720.05,725.35,438691.0,0.0,HBLENGINE,0.028573,8.695863,216.321481,0.032188,0.032188
14586,2026-01-22,5593.00,5664.00,5580.00,5659.00,82465.0,0.0,HEROMOTOCO,0.021757,10.991878,216.321481,0.040687,0.040687
14587,2026-01-22,945.00,951.40,941.10,950.20,1072924.0,0.0,HINDALCO,0.011712,11.889951,216.321481,0.044011,0.044011
14588,2026-01-22,633.80,637.00,611.60,612.20,392030.0,0.0,IIFL,-0.017099,10.534165,216.321481,0.038993,0.038993
14589,2026-01-22,513.00,528.95,512.50,528.20,526792.0,0.0,JKTYRE,0.033761,11.037786,216.321481,0.040857,0.040857
14590,2026-01-22,764.00,784.00,756.70,778.00,198702.0,0.0,JSL,0.037402,9.738245,216.321481,0.036046,0.036046
14591,2026-01-22,1003.00,1021.40,1002.10,1007.40,322819.0,0.0,LAURUSLABS,0.019739,12.035893,216.321481,0.044551,0.044551
14592,2026-01-22,288.00,288.80,285.75,286.30,1706136.0,0.0,LTF,0.017594,12.756571,216.321481,0.047219,0.047219
14593,2026-01-22,354.95,362.50,353.00,361.35,311626.0,0.0,M&MFIN,0.033462,10.088824,216.321481,0.037344,0.037344
14594,2026-01-22,363.00,368.00,361.65,367.25,2471160.0,0.0,NATIONALUM,0.015906,14.665677,216.321481,0.054285,0.054285
14595,2026-01-22,242.60,248.20,242.50,246.90,400919.0,0.0,NYKAA,0.021726,9.589283,216.321481,0.035495,0.035495
14596,2026-01-22,2849.20,2881.50,2700.00,2869.30,68639.0,0.0,RADICO,0.013028,9.138293,216.321481,0.033826,0.033826
14597,2026-01-22,1035.00,1055.50,1034.05,1049.00,3197476.0,0.0,SBIN,0.019783,11.219358,216.321481,0.041529,0.041529
14598,2026-01-22,995.05,1005.40,986.10,1002.90,759014.0,0.0,SHRIRAMFIN,0.017140,10.575565,216.321481,0.039146,0.039146
14599,2026-01-22,680.00,694.00,676.25,688.55,4929573.0,0.0,VEDL,0.017587,11.967502,216.321481,0.044298,0.044298
14636,2026-01-22,131.44,NaN,NaN,123.10,NaN,NaN,GOLDBEES,-0.087945,36.156256,NaN,0.133834,0.133834
14709,2026-01-22,299.60,NaN,NaN,270.61,NaN,NaN,SILVERBEES,-0.128975,17.680712,NaN,0.065446,0.065446

In [5]:
# Convert to dictionary
weights = dict(zip(max_date_tickers['Ticker'], max_date_tickers['Weight']))

weights

{'ANANDRATHI': 0.03822961550115751,
 'CANBK': 0.03899471170620561,
 'CUMMINSIND': 0.03651775403145329,
 'EICHERMOT': 0.0398076394154664,
 'GPIL': 0.036696505811981056,
 'HBLENGINE': 0.03218801183914666,
 'HEROMOTOCO': 0.0406867830777089,
 'HINDALCO': 0.04401102782946911,
 'IIFL': 0.03899254366985613,
 'JKTYRE': 0.04085671281092617,
 'JSL': 0.03604642154910115,
 'LAURUSLABS': 0.0445512369817669,
 'LTF': 0.04721884930281072,
 'M&MFIN': 0.03734409851580123,
 'NATIONALUM': 0.0542854662001517,
 'NYKAA': 0.03549503353744975,
 'RADICO': 0.033825680838278624,
 'SBIN': 0.04152880827580838,
 'SHRIRAMFIN': 0.03914578478812014,
 'VEDL': 0.04429808347555796,
 'GOLDBEES': 0.13383351975350305,
 'SILVERBEES': 0.06544571108827964}

In [6]:
tickers = list(max_date_tickers['Ticker'].unique()) + ['NIFTY 500']
# tickers = [
#     "ABCAPITAL",
#     "AIIL",
#     "BOSCHLTD",
#     "DATAPATTNS",
#     "DELHIVERY",
#     "ETERNAL",
#     "GOLDBEES",
#     "GVT&D",
#     "HBLENGINE",
#     "HEROMOTOCO",
#     "HINDCOPPER",
#     "HYUNDAI",
#     "IIFL",
#     "INTELLECT",
#     "LAURUSLABS",
#     "LTF",
#     "MFSL",
#     "NETWEB",
#     "POLYCAB",
#     "SYRMA",
#     "TATAINVEST",
#     "NIFTY 500"
# ]

# tickers

In [7]:
len(tickers)

23

In [8]:

import time
import logging
import pandas as pd
from truedata import TD_hist

def fetch_truedata_history(
    ticker_list: list,
    duration: str = '1 Y',
    bar_size: str = 'EOD',
    sleep_time: float = 0.1
) -> tuple[pd.DataFrame, list]:
    """
    Fetches historical data from TrueData for a list of tickers.

    Parameters
    ----------
    username : str
        TrueData username.
    password : str
        TrueData password.
    ticker_list : list
        List of ticker symbols to fetch data for.
    duration : str, optional
        Duration of data (e.g., '1 Y', '25 Y', etc.). Default is '1 Y'.
    bar_size : str, optional
        Bar size for data ('EOD', 'WEEK', etc.). Default is 'EOD'.
    sleep_time : float, optional
        Delay between API calls to avoid throttling. Default is 0.2 seconds.

    Returns
    -------
    final_df : pd.DataFrame
        Combined DataFrame of all tickers' historical data.
    error_list : list
        List of tickers that failed to fetch.
    """
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    username =  'tdwsf695'
    password = 'ocean@695'
    # username =  'td105'
    # password = 'sharma@105'
    # Initialize connection
    td_hist = TD_hist(username, password)
    df_list = []
    error_list = []
    for ticker in ticker_list:
        try:
            df = td_hist.get_historic_data([ticker], duration=duration, bar_size=bar_size)

            df['Ticker'] = ticker
            df = df.rename(columns={
                'timestamp': 'Date',
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'open': 'Open'
            })

            df_list.append(df)
            logging.info(f"Fetched data for {ticker} ({len(df)} rows).")
            time.sleep(sleep_time)

        except Exception as e:
            logging.error(f"Failed to fetch data for {ticker}: {e}")
            error_list.append(ticker)

    final_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
    return final_df, error_list

In [9]:
ticker_data = fetch_truedata_history(
        ticker_list = tickers,
        duration = '2 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0][['Ticker','Date', 'Close']]
ticker_data

(2026-01-22 09:49:48,450) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:13404 Thread:19064)
2026-01-22 09:49:48,450 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-22 09:49:48,748 - INFO - Fetched data for ANANDRATHI (497 rows).
2026-01-22 09:49:49,137 - INFO - Fetched data for CANBK (497 rows).
2026-01-22 09:49:49,529 - INFO - Fetched data for CUMMINSIND (497 rows).
2026-01-22 09:49:49,914 - INFO - Fetched data for EICHERMOT (497 rows).
2026-01-22 09:49:50,298 - INFO - Fetched data for GPIL (497 rows).
2026-01-22 09:49:50,681 - INFO - Fetched data for HBLENGINE (497 rows).
2026-01-22 09:49:51,061 - INFO - Fetched data for HEROMOTOCO (497 rows).
2026-01-22 09:49:51,432 - INFO - Fetched data for HINDALCO (497 rows).
2026-01-22 09:49:51,814 - INFO - Fetched data for IIFL (497 rows).
2026-01-22 09:49:52,201 - INFO - Fetched data for JKTYRE (497 rows).
2026-01-22 09:49:52,581 - INFO - Fetched data for JSL (497 rows).
2026-01-22 09:49:52,961 - INFO - Fetched data for LAURUSLABS (497 rows).
2026-01-22 09:49:53,342 - INFO - Fetched data for LTF (497 rows).
2026-01-22 09:49:53,724 - INFO - Fetched data for M&MFIN (497 rows).
2026-01-22 09:49:54,106 - INFO - Fetched data for NATIONALUM (497 rows).
2026-01-22 09:49:54,498 - INFO - Fetched data for NYKAA (497 rows).
2026-01-22 09:49:54,882 - INFO - Fetched data for RADICO (497 rows).
2026-01-22 09:49:55,267 - INFO - Fetched data for SBIN (497 rows).
2026-01-22 09:49:55,660 - INFO - Fetched data for SHRIRAMFIN (497 rows).
2026-01-22 09:49:56,040 - INFO - Fetched data for VEDL (497 rows).
2026-01-22 09:49:56,404 - INFO - Fetched data for GOLDBEES (497 rows).
2026-01-22 09:49:56,783 - INFO - Fetched data for SILVERBEES (497 rows).
2026-01-22 09:49:57,169 - INFO - Fetched data for NIFTY 500 (497 rows).

           Ticker       Date     Close
0      ANANDRATHI 2024-01-23   1401.20
1      ANANDRATHI 2024-01-24   1475.05
2      ANANDRATHI 2024-01-25   1521.10
3      ANANDRATHI 2024-01-29   1514.85
4      ANANDRATHI 2024-01-30   1510.40
...           ...        ...       ...
11426   NIFTY 500 2026-01-16  23485.30
11427   NIFTY 500 2026-01-19  23373.75
11428   NIFTY 500 2026-01-20  22946.65
11429   NIFTY 500 2026-01-21  22835.15
11430   NIFTY 500 2026-01-22  23136.70

[11431 rows x 3 columns]

In [10]:
ticker_data[ticker_data.duplicated(subset=['Ticker', 'Date'])]

Empty DataFrame
Columns: [Ticker, Date, Close]
Index: []

In [11]:
ticker_data = ticker_data.drop_duplicates(subset=['Ticker', 'Date'])

In [12]:
# ticker_data[ticker_data['Ticker'] == 'MOGSEC'].to_excel('MOGSEC.xlsx', index=False)

In [13]:
ticker_data.pivot(index="Date", columns="Ticker", values="Close").sort_index()

Ticker,ANANDRATHI,CANBK,CUMMINSIND,EICHERMOT,GOLDBEES,GPIL,HBLENGINE,HEROMOTOCO,HINDALCO,IIFL,...,LTF,M&MFIN,NATIONALUM,NIFTY 500,NYKAA,RADICO,SBIN,SHRIRAMFIN,SILVERBEES,VEDL
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-23,1401.20,91.20,2097.75,3616.70,52.86,143.10,454.70,4444.20,541.40,606.65,...,159.55,262.65,126.75,19206.45,163.55,1612.70,605.10,455.90,69.43,252.15
2024-01-24,1475.05,90.85,2170.80,3635.00,52.91,143.10,480.70,4433.65,565.15,594.70,...,161.25,264.60,135.60,19451.00,162.45,1668.35,618.30,460.50,70.13,262.55
2024-01-25,1521.10,93.05,2161.90,3616.45,52.72,151.95,488.95,4442.15,567.20,584.20,...,166.90,262.30,141.10,19393.00,161.10,1653.15,612.75,461.45,70.12,263.60
2024-01-29,1514.85,94.90,2255.15,3669.05,52.97,147.30,494.95,4593.50,567.90,599.45,...,167.60,270.50,145.35,19711.65,163.10,1611.50,622.95,481.80,70.43,267.80
2024-01-30,1510.40,95.45,2235.60,3704.75,53.13,148.80,504.05,4588.35,569.25,594.70,...,167.80,271.40,145.60,19574.20,165.30,1626.45,626.75,490.60,70.78,266.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-16,3092.20,157.13,4062.00,7315.00,117.78,257.55,796.05,5651.50,934.65,633.65,...,296.40,356.15,361.60,23485.30,252.85,2891.10,1042.30,995.45,269.44,682.70
2026-01-19,3097.80,156.86,4031.30,7323.50,121.10,250.20,756.30,5762.50,939.95,651.80,...,300.05,360.60,368.65,23373.75,250.80,2837.50,1038.40,1010.35,282.95,674.80
2026-01-20,3066.90,153.68,4020.90,7173.50,125.86,239.05,705.15,5580.50,928.10,630.60,...,293.80,351.90,358.95,22946.65,242.35,2753.50,1036.40,987.50,297.62,671.80
2026-01-21,3053.50,150.76,4000.70,7140.00,134.97,242.75,705.20,5538.50,939.20,622.85,...,281.35,349.65,361.50,22835.15,241.65,2832.40,1028.65,986.00,310.68,676.65
2026-01-22,3063.00,155.17,4041.00,7306.50,123.10,251.50,732.55,5659.00,950.20,612.20,...,285.30,361.35,367.05,23136.70,246.90,2869.30,1049.00,1002.90,270.61,689.20

In [14]:
ticker_data['Ticker'].nunique()

23

In [15]:
weights

{'ANANDRATHI': 0.03822961550115751,
 'CANBK': 0.03899471170620561,
 'CUMMINSIND': 0.03651775403145329,
 'EICHERMOT': 0.0398076394154664,
 'GPIL': 0.036696505811981056,
 'HBLENGINE': 0.03218801183914666,
 'HEROMOTOCO': 0.0406867830777089,
 'HINDALCO': 0.04401102782946911,
 'IIFL': 0.03899254366985613,
 'JKTYRE': 0.04085671281092617,
 'JSL': 0.03604642154910115,
 'LAURUSLABS': 0.0445512369817669,
 'LTF': 0.04721884930281072,
 'M&MFIN': 0.03734409851580123,
 'NATIONALUM': 0.0542854662001517,
 'NYKAA': 0.03549503353744975,
 'RADICO': 0.033825680838278624,
 'SBIN': 0.04152880827580838,
 'SHRIRAMFIN': 0.03914578478812014,
 'VEDL': 0.04429808347555796,
 'GOLDBEES': 0.13383351975350305,
 'SILVERBEES': 0.06544571108827964}

In [16]:
import pandas as pd
import numpy as np

def calculate_portfolio_beta_from_df(df, benchmark_name, weights_dict=None):
    """
    df: DataFrame with columns ['Ticker','Date','Close']
    benchmark_name: name used in the 'Ticker' column for your benchmark
    weights_dict: {'ABCAPITAL':0.1, 'BOSCHLTD':0.05, ...}
    """

    df['Date'] = pd.to_datetime(df['Date'])


    # Pivot → Date index, ticker columns
    price_df = df.pivot(index="Date", columns="Ticker", values="Close").sort_index()

    # keep only last 1 year
    price_df = price_df.last("252D")
    # print(price_df)

    # print(price_df)

    # Extract benchmark + stocks separately
    benchmark = price_df[benchmark_name]
    stock_prices = price_df.drop(columns=[benchmark_name])

    # daily returns
    returns = price_df.pct_change().dropna()
    stock_returns = returns.drop(columns=[benchmark_name])
    bench_ret = returns[benchmark_name]

    # weights: equal-weight if not given
    if weights_dict is None:
        n = stock_returns.shape[1]
        weights_dict = {col: 1/n for col in stock_returns.columns}

    weights = pd.Series(weights_dict).reindex(stock_returns.columns).fillna(0)

    # portfolio daily return
    portfolio_ret = (stock_returns * weights).sum(axis=1)

    # beta = Cov(portfolio, benchmark) / Var(benchmark)
    covariance = np.cov(portfolio_ret, bench_ret)[0][1]
    variance = np.var(bench_ret)

    beta = covariance / variance

    return beta, portfolio_ret, bench_ret

In [17]:
calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]

C:\Users\anike\AppData\Local\Temp\ipykernel_13404\2096940647.py:18: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  price_df = price_df.last("252D")

np.float64(0.8851907010166402)

In [18]:
current_beta = pd.DataFrame({'Beta': [calculate_portfolio_beta_from_df(ticker_data, 'NIFTY 500', weights)[0]]})
current_beta.to_excel('momentum_ratios.xlsx', index=False)
current_beta

C:\Users\anike\AppData\Local\Temp\ipykernel_13404\2096940647.py:18: FutureWarning: last is deprecated and will be removed in a future version. Please create a mask and filter using `.loc` instead
  price_df = price_df.last("252D")

       Beta
0  0.885191