In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pytz
import yfinance as yf
import pyodbc
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import time
import logging
import pandas as pd
from truedata import TD_hist

In [1]:
def fetch_truedata_history(
    ticker_list: list,
    duration: str = '1 Y',
    bar_size: str = 'EOD',
    sleep_time: float = 0.1
) -> tuple[pd.DataFrame, list]:
    """
    Fetches historical data from TrueData for a list of tickers.

    Parameters
    ----------
    username : str
        TrueData username.
    password : str
        TrueData password.
    ticker_list : list
        List of ticker symbols to fetch data for.
    duration : str, optional
        Duration of data (e.g., '1 Y', '25 Y', etc.). Default is '1 Y'.
    bar_size : str, optional
        Bar size for data ('EOD', 'WEEK', etc.). Default is 'EOD'.
    sleep_time : float, optional
        Delay between API calls to avoid throttling. Default is 0.2 seconds.

    Returns
    -------
    final_df : pd.DataFrame
        Combined DataFrame of all tickers' historical data.
    error_list : list
        List of tickers that failed to fetch.
    """
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    username =  'tdwsf695'
    password = 'ocean@695'
    # Initialize connection
    td_hist = TD_hist(username, password)
    df_list = []
    error_list = []
    for ticker in ticker_list:
        try:
            df = td_hist.get_historic_data([ticker], duration=duration, bar_size=bar_size)

            df['Ticker'] = ticker
            df = df.rename(columns={
                'timestamp': 'Date',
                'high': 'High',
                'low': 'Low',
                'close': 'Close',
                'open': 'Open'
            })

            df_list.append(df)
            logging.info(f"Fetched data for {ticker} ({len(df)} rows).")
            time.sleep(sleep_time)

        except Exception as e:
            logging.error(f"Failed to fetch data for {ticker}: {e}")
            error_list.append(ticker)

    final_df = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()
    return final_df, error_list

In [3]:
import numpy as np
import pandas as pd
from dateutil.relativedelta import relativedelta

def process_portfolio(nav_df, ticker_data, initial_value=75, output_file=None):
    """
    Process portfolio allocation and returns final dataframe with portfolio performance.

    Parameters
    ----------
    nav_df : pd.DataFrame
        Dataframe with at least ['Year-Month', 'Ticker'] columns.
    get_individual_stock_data : function
        Function to fetch OHLC data. Must accept (tickers, start_date, end_date) and return DataFrame with ['Date','Ticker','Close'].
    initial_value : float
        Initial portfolio allocation value (default=75).
    debt_ticker : str
        Ticker used as debt/alternative asset (default 'MOGSEC.NS').
    output_file : str or None
        If provided, saves the final dataframe to Excel.

    Returns
    -------
    pd.DataFrame
        Final dataframe with portfolio values.
    """
    df_lis = []
    last_month_value = {}
    last_month_quantity = {}

    year_months = nav_df['Year-Month'].unique()
    for i, year_month in enumerate(year_months):
        print(f"\nProcessing: {year_month}")
        print("Last Month Value:", last_month_value)

        tickers = nav_df[nav_df['Year-Month'] == year_month]['Ticker'].unique()
        year_month_date = pd.to_datetime(f"{year_month}-01")


        prev_month_start = (year_month_date - relativedelta(months=2)).strftime('%Y-%m-%d')
        curr_month_start = year_month_date.strftime('%Y-%m-%d')
        curr_month_end = (year_month_date + pd.offsets.MonthEnd(0)).strftime('%Y-%m-%d')

        # --- Fetch stock data ---
        # stock_data = get_individual_stock_data(tickers, prev_month_start, curr_month_end)
        stock_data = (
            ticker_data[(ticker_data['Date'] >= prev_month_start)
            & (ticker_data['Date'] <= curr_month_end) 
            & (ticker_data['Ticker'].isin(tickers))])
        stock_data = stock_data[stock_data['Date']>='2025-11-11']
        
        # % change
        stock_data['%change'] = stock_data.groupby('Ticker')['Close'].pct_change()
        # Filter current month
        stock_data_flt = stock_data[
            (stock_data['Date'] >= curr_month_start) & (stock_data['Date'] <= curr_month_end)
        ].copy()

        print(stock_data_flt)

        # --- Portfolio allocation logic ---
        if len(last_month_value) == 0:
            # First month → allocate initial portfolio equally
            allocation_per_stock = initial_value / len(tickers)
            stock_allocations = {t: allocation_per_stock for t in tickers}
        else:
            # Continue portfolio
            stock_allocations = {t: last_month_value[t] for t in tickers if t in last_month_value}

            # Pool value of dropped stocks
            dropped_stocks = [t for t in last_month_value if t not in tickers]
            dropped_value = sum(last_month_value[t] for t in dropped_stocks)

            # New stocks → share the dropped value equally
            new_stocks = [t for t in tickers if t not in last_month_value]
            if new_stocks:
                allocation_per_stock = dropped_value / len(new_stocks)
                for t in new_stocks:
                    stock_allocations[t] = allocation_per_stock

        # Apply allocations into dataframe
        for tkr, init_value in stock_allocations.items():
            tkr_idx = stock_data_flt[stock_data_flt['Ticker'] == tkr].index
            stock_data_flt.loc[tkr_idx, 'Buy_Hold_Value'] = init_value * (
                (1 + stock_data_flt.loc[tkr_idx, '%change'].fillna(0)).cumprod()
            )
            
            tkr_df = stock_data_flt[stock_data_flt['Ticker'] == tkr]
            if tkr_df.empty:
                continue

            buy_price = tkr_df.iloc[0]['Close']

            # Carry quantity if stock existed last month
            if tkr in last_month_quantity:
                quantity = last_month_quantity[tkr]
            else:
                quantity = init_value / buy_price
                
            stock_data_flt.loc[tkr_df.index, 'Buy_Price'] = buy_price
            stock_data_flt.loc[tkr_df.index, 'Quantity'] = quantity

        # --- Update last month values ---

        last_month_quantity = (
            stock_data_flt.groupby('Ticker')['Quantity'].last().to_dict()
        )
        
        last_month_value = (
            stock_data_flt.groupby('Ticker')['Buy_Hold_Value'].last().to_dict()
        )

        # --- Track total portfolio value ---
        stock_data_flt['Total_Portfolio_Value'] = (
            stock_data_flt.groupby('Date')['Buy_Hold_Value'].transform('sum')
        )

        df_lis.append(stock_data_flt)

    
    final_df = pd.concat(df_lis).reset_index(drop=True)

    # if output_file:
    #     final_df.to_excel(output_file, index=False)

    return final_df

In [4]:
import os
import pandas as pd

def prepare_and_process_portfolio(input_file, start_date, end_date, output_folder,
                                  process_portfolio,
                                  equity_allocation=75, gold_allocation=25):
    """
    Prepare portfolio dataframe with momentum stocks + GOLDBEES and process performance.

    Parameters
    ----------
    input_file : str
        Path to momentum Excel file (with End_Date, Ticker columns).
    start_date : str (YYYY-MM-DD)
        Start date for filtering.
    end_date : str (YYYY-MM-DD)
        End date for filtering.
    output_folder : str
        Folder to save output file.
    get_individual_stock_data : function
        Function to fetch stock NAV/price data.
    process_pocrtfolio : function
        Function to process equity portion of portfolio.
    process_gold : function
        Function to process gold portion of portfolio.
    equity_allocation : int, optional
        Initial allocation to equities (default=75000).
    gold_allocation : int, optional
        Initial allocation to gold (default=25000).

    Returns
    -------
    final_df : pd.DataFrame
        Combined portfolio dataframe.
    """

    # Load and clean
    nav_df = pd.read_excel(input_file).rename(columns={'End_Date': 'Date'})
    nav_df['Date'] = pd.to_datetime(nav_df['Date'])
    nav_df = (
        nav_df[(nav_df['Date'] >= start_date) & (nav_df['Date'] <= end_date)]
        .reset_index(drop=True)[['Date', 'Ticker']]
    )
    nav_df['Year-Month'] = nav_df['Date'].dt.to_period('M').astype(str)
    stocks = pd.read_excel(input_file)

    # Add GOLDBEES for each unique date
    goldbees_df = pd.DataFrame({
        'Date': nav_df['Date'].unique(),
        'Ticker': 'GOLDBEES'
    })
    goldbees_df['Year-Month'] = pd.to_datetime(goldbees_df['Date']).dt.to_period('M').astype(str)
    # print(goldbees_df)

    # Combine
    concat_df = (
        pd.concat([nav_df, goldbees_df], ignore_index=True)
          .sort_values(['Date', 'Ticker'])
          .reset_index(drop=True)
    )

    # symbol_list = stocks['Ticker'].unique()
    # ticker_data = fetch_truedata_history(
    #     ticker_list = symbol_list,
    #     duration = '5 Y',
    #     bar_size = 'EOD',
    #     sleep_time= 0.1
    # )[0]
    # final_df = process_portfolio(concat_df, ticker_data, equity_allocation)

    
    # Split
    ticker_df = concat_df.query("Ticker != 'GOLDBEES'")
    symbol_list = ticker_df['Ticker'].unique()
    ticker_data_other_stocks = fetch_truedata_history(
        ticker_list = symbol_list,
        duration = '10 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0]

    
    gold_df = concat_df.query("Ticker == 'GOLDBEES'")
    symbol_list = gold_df['Ticker'].unique()
    ticker_data_gold = fetch_truedata_history(
        ticker_list = symbol_list,
        duration = '10 Y',
        bar_size = 'EOD',
        sleep_time= 0.1
    )[0]
    # print(gold_df)

    # Process
    final_df_other_stocks = process_portfolio(ticker_df, ticker_data_other_stocks, equity_allocation)
    # final_df_gold = process_gold(gold_df, get_individual_stock_data, gold_allocation)
    final_df_gold = process_portfolio(gold_df, ticker_data_gold, gold_allocation)


    # Merge results
    final_df = (
        pd.concat([final_df_other_stocks, final_df_gold], ignore_index=True)
          .sort_values(['Date', 'Ticker'])
          .reset_index(drop=True)
    )


    # --- ensure output folder exists ---
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # --- extract middle folder name from input path ---
    middle_folder = os.path.basename(os.path.dirname(input_file))
    # e.g. for path ".../nifty500_21April2025_results/master_momentum_summary.xlsx"
    # middle_folder = "nifty500_21April2025_results"

    # --- create output filename using middle folder ---
    output_file = os.path.join(output_folder, f"{middle_folder}_gold_buy&hold_returns.xlsx")

    # --- save output ---
    # final_df.to_excel(output_file, index=False)
    print(f"✅ Final output saved to: {output_file}")

    return final_df

In [5]:
#NSE500

In [6]:
final_df = prepare_and_process_portfolio(
    input_file="Stocks/Nifty_500_2025_Apr_20_stocks_results/master_momentum_summary.xlsx",
    start_date="2025-11-01",
    end_date="2026-01-01",
    output_folder="Trials",
    process_portfolio=process_portfolio
)

import plotly.express as px

# ✅ Group by Date and calculate total portfolio value
portfolio_summary = (
    final_df.groupby("Date", as_index=False)["Buy_Hold_Value"].sum()
)

# ✅ Plot with Plotly
fig = px.line(
    portfolio_summary,
    x="Date",
    y="Buy_Hold_Value",
    title="Buy_Hold_Value Over Time",
    labels={"Date": "Date", "Buy_Hold_Value": "Buy_Hold_Value"},
    markers=True
)

fig.update_traces(line=dict(width=2))
fig.update_layout(width=1000,   # 🔑 width
                  height=500)    # 🔑 height

fig.show()

(2026-01-31 09:39:50,336) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
2026-01-31 09:39:50,336 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-31 09:39:50,834 - INFO - Fetched data for AIIL (442 rows).
2026-01-31 09:39:51,462 - INFO - Fetched data for ANANDRATHI (1026 rows).
2026-01-31 09:39:52,141 - INFO - Fetched data for CANBK (2476 rows).
2026-01-31 09:39:52,800 - INFO - Fetched data for CUMMINSIND (2476 rows).
2026-01-31 09:39:53,397 - INFO - Fetched data for DELHIVERY (917 rows).
2026-01-31 09:39:54,071 - INFO - Fetched data for FORTIS (2476 rows).
2026-01-31 09:39:54,695 - INFO - Fetched data for GLAND (1287 rows).
2026-01-31 09:39:55,366 - INFO - Fetched data for HBLENGINE (2476 rows).
2026-01-31 09:39:56,018 - INFO - Fetched data for HEROMOTOCO (2476 rows).
2026-01-31 09:39:56,679 - INFO - Fetched data for HINDALCO (2476 rows).
2026-01-31 09:39:57,507 - INFO - Fetched data for HINDCOPPER (2476 rows).
2026-01-31 09:39:58,137 - INFO - Fetched data for HYUNDAI (317 rows).
2026-01-31 09:39:58,853 - INFO - Fetched data for IIFL (2476 rows).
2026-01-31 09:39:59,583 - INFO - Fetched data for INDIANB (2476 rows).
2026-01-31 09:40:00,316 - INFO - Fetched data for INTELLECT (2476 rows).
2026-01-31 09:40:01,071 - INFO - Fetched data for LAURUSLABS (2261 rows).
2026-01-31 09:40:01,764 - INFO - Fetched data for LTF (2476 rows).
2026-01-31 09:40:02,380 - INFO - Fetched data for NETWEB (624 rows).
2026-01-31 09:40:02,993 - INFO - Fetched data for PAYTM (1043 rows).
2026-01-31 09:40:03,616 - INFO - Fetched data for POLYCAB (1684 rows).
2026-01-31 09:40:04,268 - INFO - Fetched data for ABCAPITAL (2086 rows).
2026-01-31 09:40:04,923 - INFO - Fetched data for AUBANK (2123 rows).
2026-01-31 09:40:05,629 - INFO - Fetched data for EICHERMOT (2476 rows).
2026-01-31 09:40:06,300 - INFO - Fetched data for LTIM (2362 rows).
2026-01-31 09:40:06,972 - INFO - Fetched data for M&MFIN (2476 rows).
2026-01-31 09:40:07,658 - INFO - Fetched data for MARUTI (2476 rows).
2026-01-31 09:40:08,383 - INFO - Fetched data for MCX (2476 rows).
2026-01-31 09:40:09,051 - INFO - Fetched data for MUTHOOTFIN (2476 rows).
2026-01-31 09:40:09,710 - INFO - Fetched data for NATIONALUM (2476 rows).
2026-01-31 09:40:10,308 - INFO - Fetched data for NYKAA (1049 rows).
2026-01-31 09:40:10,918 - INFO - Fetched data for SYRMA (851 rows).
2026-01-31 09:40:11,614 - INFO - Fetched data for GPIL (2476 rows).
2026-01-31 09:40:12,262 - INFO - Fetched data for JKTYRE (2476 rows).
2026-01-31 09:40:12,901 - INFO - Fetched data for JSL (2476 rows).
2026-01-31 09:40:13,537 - INFO - Fetched data for RADICO (2476 rows).
2026-01-31 09:40:14,197 - INFO - Fetched data for SBIN (2476 rows).
2026-01-31 09:40:14,823 - INFO - Fetched data for SHRIRAMFIN (2476 rows).
2026-01-31 09:40:15,484 - INFO - Fetched data for VEDL (2476 rows).
(2026-01-31 09:40:16,083) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
(2026-01-31 09:40:16,083) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
2026-01-31 09:40:16,083 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-31 09:40:16,621 - INFO - Fetched data for GOLDBEES (2473 rows).

Processing: 2025-11
Last Month Value: {}
            Date    Open    High     Low    Close   volume  oi   Ticker  \
386   2025-11-11   543.8   556.5   532.0   547.95  1343800   0     AIIL
387   2025-11-12   544.0   562.4   540.2   559.60   337825   0     AIIL
388   2025-11-13   560.0   575.8   560.0   570.80   264485   0     AIIL
389   2025-11-14   564.0   569.0   554.0   554.90   174175   0     AIIL
390   2025-11-17   550.0   568.0   544.0   556.75   645580   0     AIIL
...          ...     ...     ...     ...      ...      ...  ..      ...
36790 2025-11-24  7550.0  7550.0  7390.5  7427.00   305698   0  POLYCAB
36791 2025-11-25  7420.0  7520.0  7384.0  7439.00   130117   0  POLYCAB
36792 2025-11-26  7429.5  7568.5  7416.0  7539.00   132131   0  POLYCAB
36793 2025-11-27  7560.0  7560.0  7425.0  7479.00   170964   0  POLYCAB
36794 2025-11-28  7489.0  7520.0  7451.5  7470.00   223708   0  POLYCAB

        %change
386         NaN
387    0.021261
388    0.020014
389   -0.027856
390    0.003334
...         ...
36790 -0.012498
36791  0.001616
36792  0.013443
36793 -0.007959
36794 -0.001203

[280 rows x 9 columns]

Processing: 2025-12
Last Month Value: {'AIIL': 3.7044894607172187, 'ANANDRATHI': 3.511742682096665, 'CANBK': 4.035103286718252, 'CUMMINSIND': 3.8053044719314935, 'DELHIVERY': 3.7159962799348993, 'FORTIS': 3.4923751139933126, 'GLAND': 3.5644446845289544, 'HBLENGINE': 3.3407513578756785, 'HEROMOTOCO': 4.2739963082602666, 'HINDALCO': 3.819212598425195, 'HINDCOPPER': 3.409090909090909, 'HYUNDAI': 3.702249575551783, 'IIFL': 4.013176144244105, 'INDIANB': 3.7601538195644673, 'INTELLECT': 3.7964100464100463, 'LAURUSLABS': 3.9236709952318143, 'LTF': 3.9698779867819027, 'NETWEB': 3.532859146463635, 'PAYTM': 3.7162314272850074, 'POLYCAB': 3.6572230563352695}
            Date     Open     High      Low    Close   volume  oi      Ticker  \
6378  2025-12-01  4490.00  4553.20  4480.10  4544.20   421940   0  CUMMINSIND
6379  2025-12-02  4544.20  4574.00  4500.00  4514.50   448981   0  CUMMINSIND
6380  2025-12-03  4515.00  4527.00  4450.30  4514.10   410207   0  CUMMINSIND
6381  2025-12-04  4525.00  4552.50  4430.00  4459.30   339985   0  CUMMINSIND
6382  2025-12-05  4459.30  4491.30  4437.70  4468.90   560759   0  CUMMINSIND
...          ...      ...      ...      ...      ...      ...  ..         ...
60139 2025-12-24   732.20   743.40   725.70   733.85   883395   0       SYRMA
60140 2025-12-26   733.80   741.90   727.00   737.70   564067   0       SYRMA
60141 2025-12-29   736.90   736.95   709.20   712.95   783251   0       SYRMA
60142 2025-12-30   712.95   737.00   711.00   722.70  1190014   0       SYRMA
60143 2025-12-31   722.40   735.00   722.25   733.15   377297   0       SYRMA

        %change
6378   0.014489
6379  -0.006536
6380  -0.000089
6381  -0.012140
6382   0.002153
...         ...
60139  0.000477
60140  0.005246
60141 -0.033550
60142  0.013676
60143  0.014460

[440 rows x 9 columns]

Processing: 2026-01
Last Month Value: {'ABCAPITAL': 3.676215404870192, 'AUBANK': 3.831011270199248, 'CUMMINSIND': 3.767160527388881, 'EICHERMOT': 3.814932840869398, 'HBLENGINE': 3.495021122510561, 'HEROMOTOCO': 3.9946931241347476, 'HINDALCO': 4.189133858267712, 'INDIANB': 3.6175682682336685, 'LAURUSLABS': 4.215278482296845, 'LTF': 4.015632943568888, 'LTIM': 3.6598938735181554, 'M&MFIN': 3.9880716182940708, 'MARUTI': 3.86426597824375, 'MCX': 4.067939825050364, 'MUTHOOTFIN': 3.746151713918917, 'NATIONALUM': 4.448669374126802, 'NYKAA': 3.650077738472917, 'PAYTM': 3.655166591625394, 'POLYCAB': 3.730171682224688, 'SYRMA': 3.2890637281655857}
            Date     Open     High      Low    Close    volume  oi  \
1448  2026-01-01  3103.00  3103.60  3062.00  3094.90    265253   0
1449  2026-01-02  3074.00  3107.50  3055.00  3079.40    149134   0
1450  2026-01-05  3099.00  3145.00  3082.60  3123.60    154296   0
1451  2026-01-06  3105.60  3170.00  3101.00  3149.20    183406   0
1452  2026-01-07  3150.00  3180.50  3150.00  3166.10    182284   0
...          ...      ...      ...      ...      ...       ...  ..
77491 2026-01-23   685.00   699.00   681.45   684.15  21435331   0
77492 2026-01-27   697.10   707.35   694.55   705.45  18667388   0
77493 2026-01-28   711.10   741.95   710.10   737.10  26645434   0
77494 2026-01-29   745.25   769.80   743.00   766.35  30290476   0
77495 2026-01-30   755.00   755.00   675.10   681.55  54628339   0

           Ticker   %change
1448   ANANDRATHI -0.005623
1449   ANANDRATHI -0.005008
1450   ANANDRATHI  0.014353
1451   ANANDRATHI  0.008196
1452   ANANDRATHI  0.005366
...           ...       ...
77491        VEDL  0.008104
77492        VEDL  0.031134
77493        VEDL  0.044865
77494        VEDL  0.039683
77495        VEDL -0.110654

[400 rows x 9 columns]

Processing: 2025-11
Last Month Value: {}
           Date    Open    High     Low   Close    volume  oi    Ticker  \
2417 2025-11-11  102.83  103.72  102.80  103.29  33803897   0  GOLDBEES
2418 2025-11-12  102.98  102.98  102.15  102.69  29596247   0  GOLDBEES
2419 2025-11-13  104.16  105.46  104.16  105.37  33205778   0  GOLDBEES
2420 2025-11-14  105.12  105.12  103.56  103.81  28533187   0  GOLDBEES
2421 2025-11-17  103.36  103.36  101.00  101.94  27817135   0  GOLDBEES
2422 2025-11-18  100.87  101.12  100.01  100.91  35663185   0  GOLDBEES
2423 2025-11-19  101.25  102.60  101.25  102.23  22235008   0  GOLDBEES
2424 2025-11-20  101.50  102.07  101.02  101.55  20599534   0  GOLDBEES
2425 2025-11-21  101.65  102.29  100.61  102.00  23459553   0  GOLDBEES
2426 2025-11-24  101.99  102.34  101.55  102.23  24131584   0  GOLDBEES
2427 2025-11-25  103.22  104.00  103.10  103.46  24988736   0  GOLDBEES
2428 2025-11-26  103.91  104.35  103.91  104.18  23022226   0  GOLDBEES
2429 2025-11-27  104.10  104.40  103.84  104.11  19397032   0  GOLDBEES
2430 2025-11-28  104.60  104.98  104.31  104.62  18626408   0  GOLDBEES

       %change
2417       NaN
2418 -0.005809
2419  0.026098
2420 -0.014805
2421 -0.018014
2422 -0.010104
2423  0.013081
2424 -0.006652
2425  0.004431
2426  0.002255
2427  0.012032
2428  0.006959
2429 -0.000672
2430  0.004899

Processing: 2025-12
Last Month Value: {'GOLDBEES': 25.321909187723872}
           Date    Open    High     Low   Close    volume  oi    Ticker  \
2431 2025-12-01  106.09  106.80  105.77  106.72  32935620   0  GOLDBEES
2432 2025-12-02  106.65  106.65  105.39  105.63  26342500   0  GOLDBEES
2433 2025-12-03  106.25  106.70  106.24  106.51  25811907   0  GOLDBEES
2434 2025-12-04  106.67  106.96  105.70  105.92  27124243   0  GOLDBEES
2435 2025-12-05  106.27  107.02  105.82  106.89  22860218   0  GOLDBEES
2436 2025-12-08  106.77  106.96  106.11  106.85  26109955   0  GOLDBEES
2437 2025-12-09  106.76  106.76  105.50  106.28  22835801   0  GOLDBEES
2438 2025-12-10  106.85  106.85  106.10  106.23  21093711   0  GOLDBEES
2439 2025-12-11  106.86  107.28  106.37  107.15  20249677   0  GOLDBEES
2440 2025-12-12  108.20  109.98  108.20  109.61  42813407   0  GOLDBEES
2441 2025-12-15  110.45  111.09  109.72  110.95  44275839   0  GOLDBEES
2442 2025-12-16  109.46  110.05  109.20  109.56  36341576   0  GOLDBEES
2443 2025-12-17  110.13  111.77  109.46  109.99  48571973   0  GOLDBEES
2444 2025-12-18  110.05  110.58  109.77  109.88  26801568   0  GOLDBEES
2445 2025-12-19  109.79  110.09  109.32  109.82  25353023   0  GOLDBEES
2446 2025-12-22  110.70  111.55  110.34  111.39  66926289   0  GOLDBEES
2447 2025-12-23  112.52  113.74  112.52  113.10  45892148   0  GOLDBEES
2448 2025-12-24  113.49  115.00  112.99  113.21  47649347   0  GOLDBEES
2449 2025-12-26  113.37  114.48  113.37  114.31  46010219   0  GOLDBEES
2450 2025-12-29  115.44  115.45  112.00  113.03  73386481   0  GOLDBEES
2451 2025-12-30  111.78  117.00  110.10  111.17  55356981   0  GOLDBEES
2452 2025-12-31  111.17  111.48  109.75  110.11  40043851   0  GOLDBEES

       %change
2431  0.020073
2432 -0.010214
2433  0.008331
2434 -0.005539
2435  0.009158
2436 -0.000374
2437 -0.005335
2438 -0.000470
2439  0.008660
2440  0.022958
2441  0.012225
2442 -0.012528
2443  0.003925
2444 -0.001000
2445 -0.000546
2446  0.014296
2447  0.015351
2448  0.000973
2449  0.009716
2450 -0.011198
2451 -0.016456
2452 -0.009535

Processing: 2026-01
Last Month Value: {'GOLDBEES': 26.650692225772094}
           Date    Open    High     Low   Close     volume  oi    Ticker  \
2453 2026-01-01  110.35  110.65  109.70  110.52   24308237   0  GOLDBEES
2454 2026-01-02  111.62  111.98  110.92  111.82   37641644   0  GOLDBEES
2455 2026-01-05  112.16  113.20  111.84  112.92   50850027   0  GOLDBEES
2456 2026-01-06  113.62  113.71  113.01  113.14   45693265   0  GOLDBEES
2457 2026-01-07  113.51  113.99  112.46  112.91   39011859   0  GOLDBEES
2458 2026-01-08  112.73  112.96  111.42  112.29   37515879   0  GOLDBEES
2459 2026-01-09  113.26  113.88  112.61  113.61   39284191   0  GOLDBEES
2460 2026-01-12  115.70  117.00  114.81  116.76   70988427   0  GOLDBEES
2461 2026-01-13  116.98  117.14  116.00  116.37   59657307   0  GOLDBEES
2462 2026-01-14  117.83  118.49  116.36  118.01   77320821   0  GOLDBEES
2463 2026-01-16  117.79  118.40  117.04  117.78   65356923   0  GOLDBEES
2464 2026-01-19  119.15  122.90  118.56  121.10   91475080   0  GOLDBEES
2465 2026-01-20  121.99  126.90  120.20  125.86  171440092   0  GOLDBEES
2466 2026-01-21  127.00  135.90  127.00  134.97  248755481   0  GOLDBEES
2467 2026-01-22  131.44  131.84  119.00  124.34  233048051   0  GOLDBEES
2468 2026-01-23  129.10  132.48  126.00  127.42  141941218   0  GOLDBEES
2469 2026-01-27  130.55  134.00  129.03  131.45  139657546   0  GOLDBEES
2470 2026-01-28  132.00  137.10  132.00  135.82  184193702   0  GOLDBEES
2471 2026-01-29  143.00  148.14  141.64  146.53  271824296   0  GOLDBEES
2472 2026-01-30  138.70  142.80  127.10  131.12  352204561   0  GOLDBEES

       %change
2453  0.003724
2454  0.011763
2455  0.009837
2456  0.001948
2457 -0.002033
2458 -0.005491
2459  0.011755
2460  0.027726
2461 -0.003340
2462  0.014093
2463 -0.001949
2464  0.028188
2465  0.039306
2466  0.072382
2467 -0.078758
2468  0.024771
2469  0.031628
2470  0.033245
2471  0.078854
2472 -0.105166
✅ Final output saved to: Trials\Nifty_500_2025_Apr_20_stocks_results_gold_buy&hold_returns.xlsx

In [7]:
final_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value
0,2025-11-11,543.8,556.50,532.00,547.95,1343800,0,AIIL,NaN,3.750000,547.95,0.006844,75.000000
1,2025-11-11,3125.0,3139.90,3040.00,3084.90,151685,0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.000000
2,2025-11-11,140.6,141.39,137.95,140.87,21813910,0,CANBK,NaN,3.750000,140.87,0.026620,75.000000
3,2025-11-11,4349.1,4420.00,4290.90,4414.20,395014,0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.000000
4,2025-11-11,430.1,434.90,424.45,430.10,4395363,0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,2026-01-30,234.8,238.50,233.05,237.50,8061305,0,NYKAA,-0.001681,3.269445,265.75,0.013891,74.683939
1172,2026-01-30,2700.0,2849.00,2694.90,2828.10,626081,0,RADICO,0.046940,3.184223,3253.90,0.001141,74.683939
1173,2026-01-30,1064.0,1082.50,1060.40,1077.15,9480769,0,SBIN,0.010270,4.072755,984.75,0.003771,74.683939
1174,2026-01-30,1025.0,1029.30,1010.15,1020.00,6464610,0,SHRIRAMFIN,-0.002738,3.802469,1019.70,0.003642,74.683939
1175,2026-01-30,755.0,755.00,675.10,681.55,54628339,0,VEDL,-0.110654,4.187794,602.65,0.006162,74.683939

In [8]:
final_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value
0,2025-11-11,543.8,556.50,532.00,547.95,1343800,0,AIIL,NaN,3.750000,547.95,0.006844,75.000000
1,2025-11-11,3125.0,3139.90,3040.00,3084.90,151685,0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.000000
2,2025-11-11,140.6,141.39,137.95,140.87,21813910,0,CANBK,NaN,3.750000,140.87,0.026620,75.000000
3,2025-11-11,4349.1,4420.00,4290.90,4414.20,395014,0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.000000
4,2025-11-11,430.1,434.90,424.45,430.10,4395363,0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,2026-01-30,234.8,238.50,233.05,237.50,8061305,0,NYKAA,-0.001681,3.269445,265.75,0.013891,74.683939
1172,2026-01-30,2700.0,2849.00,2694.90,2828.10,626081,0,RADICO,0.046940,3.184223,3253.90,0.001141,74.683939
1173,2026-01-30,1064.0,1082.50,1060.40,1077.15,9480769,0,SBIN,0.010270,4.072755,984.75,0.003771,74.683939
1174,2026-01-30,1025.0,1029.30,1010.15,1020.00,6464610,0,SHRIRAMFIN,-0.002738,3.802469,1019.70,0.003642,74.683939
1175,2026-01-30,755.0,755.00,675.10,681.55,54628339,0,VEDL,-0.110654,4.187794,602.65,0.006162,74.683939

In [9]:
old_df = final_df[~((final_df['Date']>'2025-11-30') & (final_df['Ticker']=='GOLDBEES'))]
old_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value
0,2025-11-11,543.8,556.50,532.00,547.95,1343800,0,AIIL,NaN,3.750000,547.95,0.006844,75.000000
1,2025-11-11,3125.0,3139.90,3040.00,3084.90,151685,0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.000000
2,2025-11-11,140.6,141.39,137.95,140.87,21813910,0,CANBK,NaN,3.750000,140.87,0.026620,75.000000
3,2025-11-11,4349.1,4420.00,4290.90,4414.20,395014,0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.000000
4,2025-11-11,430.1,434.90,424.45,430.10,4395363,0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,2026-01-30,234.8,238.50,233.05,237.50,8061305,0,NYKAA,-0.001681,3.269445,265.75,0.013891,74.683939
1172,2026-01-30,2700.0,2849.00,2694.90,2828.10,626081,0,RADICO,0.046940,3.184223,3253.90,0.001141,74.683939
1173,2026-01-30,1064.0,1082.50,1060.40,1077.15,9480769,0,SBIN,0.010270,4.072755,984.75,0.003771,74.683939
1174,2026-01-30,1025.0,1029.30,1010.15,1020.00,6464610,0,SHRIRAMFIN,-0.002738,3.802469,1019.70,0.003642,74.683939
1175,2026-01-30,755.0,755.00,675.10,681.55,54628339,0,VEDL,-0.110654,4.187794,602.65,0.006162,74.683939

In [10]:
old_df['Ticker'].unique()

array(['AIIL', 'ANANDRATHI', 'CANBK', 'CUMMINSIND', 'DELHIVERY', 'FORTIS',
       'GLAND', 'GOLDBEES', 'HBLENGINE', 'HEROMOTOCO', 'HINDALCO',
       'HINDCOPPER', 'HYUNDAI', 'IIFL', 'INDIANB', 'INTELLECT',
       'LAURUSLABS', 'LTF', 'NETWEB', 'PAYTM', 'POLYCAB', 'ABCAPITAL',
       'AUBANK', 'EICHERMOT', 'LTIM', 'M&MFIN', 'MARUTI', 'MCX',
       'MUTHOOTFIN', 'NATIONALUM', 'NYKAA', 'SYRMA', 'GPIL', 'JKTYRE',
       'JSL', 'RADICO', 'SBIN', 'SHRIRAMFIN', 'VEDL'], dtype=object)

In [11]:
df = fetch_truedata_history(
    ticker_list = ['GOLDBEES', 'SILVERBEES', 'MOGSEC'],
    duration = '5 Y',
    bar_size = 'EOD',
    sleep_time= 0.1
)[0]
df = df[["Date","Ticker", "Open", "Close"]]
df['%change'] = df['Close'].pct_change()
df = df[df['Date'] >= '2025-12-01']
# df.to_excel('C:\\Users\\Admin\\Momentum\\Automating Momentum True Data\\Trials\\nse200_Nifty_200_2025_Aug_nse200_nse200_nse200_nse200_nse200_returns.xlsx', index=False)
df

(2026-01-31 09:40:18,530) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
(2026-01-31 09:40:18,530) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
(2026-01-31 09:40:18,530) WARNING :: Connected successfully to TrueData Historical Data Service...  (PID:12212 Thread:14348)
2026-01-31 09:40:18,530 - WARNING - Connected successfully to TrueData Historical Data Service...
2026-01-31 09:40:19,036 - INFO - Fetched data for GOLDBEES (1240 rows).
2026-01-31 09:40:19,613 - INFO - Fetched data for SILVERBEES (988 rows).
2026-01-31 09:40:20,212 - INFO - Fetched data for MOGSEC (1150 rows).

           Date    Ticker    Open   Close   %change
1198 2025-12-01  GOLDBEES  106.09  106.72  0.020073
1199 2025-12-02  GOLDBEES  106.65  105.63 -0.010214
1200 2025-12-03  GOLDBEES  106.25  106.51  0.008331
1201 2025-12-04  GOLDBEES  106.67  105.92 -0.005539
1202 2025-12-05  GOLDBEES  106.27  106.89  0.009158
...         ...       ...     ...     ...       ...
3373 2026-01-23    MOGSEC   62.90   62.99  0.000953
3374 2026-01-27    MOGSEC   62.99   62.77 -0.003493
3375 2026-01-28    MOGSEC   62.94   62.99  0.003505
3376 2026-01-29    MOGSEC   62.83   62.90 -0.001429
3377 2026-01-30    MOGSEC   62.71   63.06  0.002544

[126 rows x 5 columns]

In [12]:
ticker_weights = {'GOLDBEES':0.6, 'SILVERBEES':0.2, 'MOGSEC':0.2}
# factor = 51214.0199725867
factor = 25.32190919


ticker_value = {ticker: weight * factor for ticker, weight in ticker_weights.items()}
ticker_value

{'GOLDBEES': 15.193145514, 'SILVERBEES': 5.064381838, 'MOGSEC': 5.064381838}

In [13]:
df['BaseValue'] = df['Ticker'].map(ticker_value)
# Assign values
df['Value'] = df['Ticker'].map(ticker_value)
# Convert %change to numeric (if needed)
df['%change'] = pd.to_numeric(df['%change'])
# Sort (important for cumprod)
df = df.sort_values(['Ticker', 'Date'])

# Daily growth factor
df['ret_factor'] = 1 + df['%change']

# Cumulative factor per ticker
df['cum_factor'] = df.groupby('Ticker')['ret_factor'].cumprod()

# FINAL DAILY VALUE
df['Value_On_Date'] = df['BaseValue'] * df['cum_factor']

df = df[['Date', 'Ticker', 'Open', 'Close', 'Value_On_Date', '%change']].rename(columns={'Value_On_Date':'Buy_Hold_Value'}).sort_values(by='Date')
df

           Date      Ticker    Open   Close  Buy_Hold_Value   %change
1198 2025-12-01    GOLDBEES  106.09  106.72       15.498112  0.020073
2186 2025-12-01  SILVERBEES  166.02  166.21        5.369337  0.060216
3336 2025-12-01      MOGSEC   62.70   62.82        5.053121 -0.002224
1199 2025-12-02    GOLDBEES  106.65  105.63       15.339820 -0.010214
2187 2025-12-02  SILVERBEES  167.01  165.34        5.341232 -0.005234
...         ...         ...     ...     ...             ...       ...
1238 2026-01-29    GOLDBEES  143.00  146.53       21.279407  0.078854
3376 2026-01-29      MOGSEC   62.83   62.90        5.059556 -0.001429
3377 2026-01-30      MOGSEC   62.71   63.06        5.072426  0.002544
1239 2026-01-30    GOLDBEES  138.70  131.12       19.041534 -0.105166
2227 2026-01-30  SILVERBEES  329.00  286.48        9.254603 -0.185928

[126 rows x 6 columns]

In [14]:
# df

In [15]:
df['Buy_Value'] = df.groupby('Ticker')['Buy_Hold_Value'].transform('first')
df['Buy_Price'] = df.groupby('Ticker')['Close'].transform('first')
df['Quantity'] = df['Buy_Value'] / df['Buy_Price']
df

,Date,Ticker,Open,Close,Buy_Hold_Value,%change,Buy_Value,Buy_Price,Quantity
1198,2025-12-01,GOLDBEES,106.09,106.72,15.498112,0.020073,15.498112,106.72,0.145222
2186,2025-12-01,SILVERBEES,166.02,166.21,5.369337,0.060216,5.369337,166.21,0.032305
3336,2025-12-01,MOGSEC,62.70,62.82,5.053121,-0.002224,5.053121,62.82,0.080438
1199,2025-12-02,GOLDBEES,106.65,105.63,15.339820,-0.010214,15.498112,106.72,0.145222
2187,2025-12-02,SILVERBEES,167.01,165.34,5.341232,-0.005234,5.369337,166.21,0.032305
...,...,...,...,...,...,...,...,...,...
1238,2026-01-29,GOLDBEES,143.00,146.53,21.279407,0.078854,15.498112,106.72,0.145222
3376,2026-01-29,MOGSEC,62.83,62.90,5.059556,-0.001429,5.053121,62.82,0.080438
3377,2026-01-30,MOGSEC,62.71,63.06,5.072426,0.002544,5.053121,62.82,0.080438
1239,2026-01-30,GOLDBEES,138.70,131.12,19.041534,-0.105166,15.498112,106.72,0.145222
2227,2026-01-30,SILVERBEES,329.00,286.48,9.254603,-0.185928,5.369337,166.21,0.032305

In [16]:
conc_df = pd.concat([old_df, df])
conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value,Buy_Value
0,2025-11-11,543.80,556.50,532.00,547.95,1343800.0,0.0,AIIL,NaN,3.750000,547.95,0.006844,75.0,NaN
1,2025-11-11,3125.00,3139.90,3040.00,3084.90,151685.0,0.0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.0,NaN
2,2025-11-11,140.60,141.39,137.95,140.87,21813910.0,0.0,CANBK,NaN,3.750000,140.87,0.026620,75.0,NaN
3,2025-11-11,4349.10,4420.00,4290.90,4414.20,395014.0,0.0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.0,NaN
4,2025-11-11,430.10,434.90,424.45,430.10,4395363.0,0.0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,2026-01-29,143.00,NaN,NaN,146.53,NaN,NaN,GOLDBEES,0.078854,21.279407,106.72,0.145222,NaN,15.498112
3376,2026-01-29,62.83,NaN,NaN,62.90,NaN,NaN,MOGSEC,-0.001429,5.059556,62.82,0.080438,NaN,5.053121
3377,2026-01-30,62.71,NaN,NaN,63.06,NaN,NaN,MOGSEC,0.002544,5.072426,62.82,0.080438,NaN,5.053121
1239,2026-01-30,138.70,NaN,NaN,131.12,NaN,NaN,GOLDBEES,-0.105166,19.041534,106.72,0.145222,NaN,15.498112
2227,2026-01-30,329.00,NaN,NaN,286.48,NaN,NaN,SILVERBEES,-0.185928,9.254603,166.21,0.032305,NaN,5.369337

In [17]:
import plotly.express as px

# ✅ Group by Date and calculate total portfolio value
portfolio_summary = (
    conc_df.groupby("Date", as_index=False)["Buy_Hold_Value"].sum()
)
# ✅ Plot with Plotly
fig = px.line(
    portfolio_summary,
    x="Date",
    y="Buy_Hold_Value",
    title="Buy_Hold_Value Over Time",
    labels={"Date": "Date", "Buy_Hold_Value": "Buy_Hold_Value"},
    markers=True
)

fig.update_traces(line=dict(width=2))
fig.update_layout(width=1000,   # 🔑 width
                  height=500)    # 🔑 height
fig.show()

In [18]:
# Momentum/Automating Momentum True Data/Trials/Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx

In [19]:
 # conc_df.to_excel('C://Users//Admin//Momentum//Automating Momentum True Data//Trials//Nifty_500_2025_Apr_20_stocks_results_GoldSilverDebt_buy&hold_returns.xlsx', index=False)

In [20]:
conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value,Buy_Value
0,2025-11-11,543.80,556.50,532.00,547.95,1343800.0,0.0,AIIL,NaN,3.750000,547.95,0.006844,75.0,NaN
1,2025-11-11,3125.00,3139.90,3040.00,3084.90,151685.0,0.0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.0,NaN
2,2025-11-11,140.60,141.39,137.95,140.87,21813910.0,0.0,CANBK,NaN,3.750000,140.87,0.026620,75.0,NaN
3,2025-11-11,4349.10,4420.00,4290.90,4414.20,395014.0,0.0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.0,NaN
4,2025-11-11,430.10,434.90,424.45,430.10,4395363.0,0.0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,2026-01-29,143.00,NaN,NaN,146.53,NaN,NaN,GOLDBEES,0.078854,21.279407,106.72,0.145222,NaN,15.498112
3376,2026-01-29,62.83,NaN,NaN,62.90,NaN,NaN,MOGSEC,-0.001429,5.059556,62.82,0.080438,NaN,5.053121
3377,2026-01-30,62.71,NaN,NaN,63.06,NaN,NaN,MOGSEC,0.002544,5.072426,62.82,0.080438,NaN,5.053121
1239,2026-01-30,138.70,NaN,NaN,131.12,NaN,NaN,GOLDBEES,-0.105166,19.041534,106.72,0.145222,NaN,15.498112
2227,2026-01-30,329.00,NaN,NaN,286.48,NaN,NaN,SILVERBEES,-0.185928,9.254603,166.21,0.032305,NaN,5.369337

In [21]:
conc_df['Asset Type'] = np.where(
    conc_df['Ticker'] == 'GOLDBEES', 'Gold',
    np.where(
        conc_df['Ticker'] == 'SILVERBEES', 'Silver',
        np.where(
            conc_df['Ticker'] == 'MOGSEC', 'Debt',
            'Equities'
        )
    )
)

conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value,Buy_Value,Asset Type
0,2025-11-11,543.80,556.50,532.00,547.95,1343800.0,0.0,AIIL,NaN,3.750000,547.95,0.006844,75.0,NaN,Equities
1,2025-11-11,3125.00,3139.90,3040.00,3084.90,151685.0,0.0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.0,NaN,Equities
2,2025-11-11,140.60,141.39,137.95,140.87,21813910.0,0.0,CANBK,NaN,3.750000,140.87,0.026620,75.0,NaN,Equities
3,2025-11-11,4349.10,4420.00,4290.90,4414.20,395014.0,0.0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.0,NaN,Equities
4,2025-11-11,430.10,434.90,424.45,430.10,4395363.0,0.0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.0,NaN,Equities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,2026-01-29,143.00,NaN,NaN,146.53,NaN,NaN,GOLDBEES,0.078854,21.279407,106.72,0.145222,NaN,15.498112,Gold
3376,2026-01-29,62.83,NaN,NaN,62.90,NaN,NaN,MOGSEC,-0.001429,5.059556,62.82,0.080438,NaN,5.053121,Debt
3377,2026-01-30,62.71,NaN,NaN,63.06,NaN,NaN,MOGSEC,0.002544,5.072426,62.82,0.080438,NaN,5.053121,Debt
1239,2026-01-30,138.70,NaN,NaN,131.12,NaN,NaN,GOLDBEES,-0.105166,19.041534,106.72,0.145222,NaN,15.498112,Gold
2227,2026-01-30,329.00,NaN,NaN,286.48,NaN,NaN,SILVERBEES,-0.185928,9.254603,166.21,0.032305,NaN,5.369337,Silver

In [22]:
# conc_df = conc_df[conc_df['Date']<='2026-01-06']
conc_df = conc_df[conc_df['Date'] <= pd.Timestamp.today().normalize()]
conc_df

,Date,Open,High,Low,Close,volume,oi,Ticker,%change,Buy_Hold_Value,Buy_Price,Quantity,Total_Portfolio_Value,Buy_Value,Asset Type
0,2025-11-11,543.80,556.50,532.00,547.95,1343800.0,0.0,AIIL,NaN,3.750000,547.95,0.006844,75.0,NaN,Equities
1,2025-11-11,3125.00,3139.90,3040.00,3084.90,151685.0,0.0,ANANDRATHI,NaN,3.750000,3084.90,0.001216,75.0,NaN,Equities
2,2025-11-11,140.60,141.39,137.95,140.87,21813910.0,0.0,CANBK,NaN,3.750000,140.87,0.026620,75.0,NaN,Equities
3,2025-11-11,4349.10,4420.00,4290.90,4414.20,395014.0,0.0,CUMMINSIND,NaN,3.750000,4414.20,0.000850,75.0,NaN,Equities
4,2025-11-11,430.10,434.90,424.45,430.10,4395363.0,0.0,DELHIVERY,NaN,3.750000,430.10,0.008719,75.0,NaN,Equities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,2026-01-29,143.00,NaN,NaN,146.53,NaN,NaN,GOLDBEES,0.078854,21.279407,106.72,0.145222,NaN,15.498112,Gold
3376,2026-01-29,62.83,NaN,NaN,62.90,NaN,NaN,MOGSEC,-0.001429,5.059556,62.82,0.080438,NaN,5.053121,Debt
3377,2026-01-30,62.71,NaN,NaN,63.06,NaN,NaN,MOGSEC,0.002544,5.072426,62.82,0.080438,NaN,5.053121,Debt
1239,2026-01-30,138.70,NaN,NaN,131.12,NaN,NaN,GOLDBEES,-0.105166,19.041534,106.72,0.145222,NaN,15.498112,Gold
2227,2026-01-30,329.00,NaN,NaN,286.48,NaN,NaN,SILVERBEES,-0.185928,9.254603,166.21,0.032305,NaN,5.369337,Silver

In [23]:
conc_df.to_excel('Momentum_Maxfolio.xlsx', index=False)